
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 27 2024 00:00:58 EST (Nov 27 2024 05:00:58 UTC)

// Verification Directory fv/riscv_core 

module riscv_core(i_rstn, i_clk, o_imem_en, o_imem_addr, i_imem_read,
     o_dmem_en, o_dmem_we, o_dmem_addr, i_dmem_read, o_dmem_write,
     i_scan_en, i_test_mode, i_tdi, o_tdo);
  input i_rstn, i_clk, i_scan_en, i_test_mode, i_tdi;
  input [31:0] i_imem_read, i_dmem_read;
  output o_imem_en, o_dmem_en, o_dmem_we, o_tdo;
  output [8:0] o_imem_addr, o_dmem_addr;
  output [31:0] o_dmem_write;
  wire i_rstn, i_clk, i_scan_en, i_test_mode, i_tdi;
  wire [31:0] i_imem_read, i_dmem_read;
  wire o_imem_en, o_dmem_en, o_dmem_we, o_tdo;
  wire [8:0] o_imem_addr, o_dmem_addr;
  wire [31:0] o_dmem_write;
  wire [31:0] ex_to_me_result;
  wire [31:0] id_to_ex_imm;
  wire [31:0] ex_to_if_pc_target;
  wire [31:0] u_fetch_pc_value;
  wire [2:0] id_to_ex_alu_op;
  wire [31:0] if_to_id_instr;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, ex_to_if_pc_transfer,
       ex_to_me_we, id_to_ex_arith, id_to_ex_branch, id_to_ex_jump;
  wire id_to_ex_rw, id_to_ex_src_imm, n_7, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_579, n_580, n_581, n_582, n_583, n_584, n_585;
  wire n_586, n_587, n_588, n_589, n_590, n_591, u_execute_branch_taken;
  assign o_tdo = 1'b0;
  assign o_dmem_write[0] = 1'b0;
  assign o_dmem_write[1] = 1'b0;
  assign o_dmem_write[2] = 1'b0;
  assign o_dmem_write[3] = 1'b0;
  assign o_dmem_write[4] = 1'b0;
  assign o_dmem_write[5] = 1'b0;
  assign o_dmem_write[6] = 1'b0;
  assign o_dmem_write[7] = 1'b0;
  assign o_dmem_write[8] = 1'b0;
  assign o_dmem_write[9] = 1'b0;
  assign o_dmem_write[10] = 1'b0;
  assign o_dmem_write[11] = 1'b0;
  assign o_dmem_write[12] = 1'b0;
  assign o_dmem_write[13] = 1'b0;
  assign o_dmem_write[14] = 1'b0;
  assign o_dmem_write[15] = 1'b0;
  assign o_dmem_write[16] = 1'b0;
  assign o_dmem_write[17] = 1'b0;
  assign o_dmem_write[18] = 1'b0;
  assign o_dmem_write[19] = 1'b0;
  assign o_dmem_write[20] = 1'b0;
  assign o_dmem_write[21] = 1'b0;
  assign o_dmem_write[22] = 1'b0;
  assign o_dmem_write[23] = 1'b0;
  assign o_dmem_write[24] = 1'b0;
  assign o_dmem_write[25] = 1'b0;
  assign o_dmem_write[26] = 1'b0;
  assign o_dmem_write[27] = 1'b0;
  assign o_dmem_write[28] = 1'b0;
  assign o_dmem_write[29] = 1'b0;
  assign o_dmem_write[30] = 1'b0;
  assign o_dmem_write[31] = 1'b0;
  assign o_imem_en = 1'b1;
  DFFRHQX1 \u_execute_buffer_alu_result_reg[10] (.RN (i_rstn), .CK
       (i_clk), .D (n_146), .Q (ex_to_me_result[10]));
  OAI2BB1X1 g4028__2398(.A0N (id_to_ex_imm[10]), .A1N (n_142), .B0
       (n_144), .Y (n_146));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[9] (.RN (i_rstn), .CK
       (i_clk), .D (n_145), .Q (ex_to_me_result[9]));
  OAI2BB1X1 g4029__5107(.A0N (id_to_ex_imm[9]), .A1N (n_136), .B0
       (n_141), .Y (n_145));
  AOI22X1 g4032__6260(.A0 (n_140), .A1 (n_138), .B0 (n_139), .B1
       (ex_to_me_result[10]), .Y (n_144));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[8] (.RN (i_rstn), .CK
       (i_clk), .D (n_143), .Q (ex_to_me_result[8]));
  OAI2BB1X1 g4024__4319(.A0N (id_to_ex_imm[8]), .A1N (n_128), .B0
       (n_133), .Y (n_143));
  OAI2BB1X1 g4046__8428(.A0N (n_135), .A1N (n_137), .B0 (n_134), .Y
       (n_142));
  AOI22X1 g4039__5526(.A0 (n_140), .A1 (n_131), .B0 (n_139), .B1
       (ex_to_me_result[9]), .Y (n_141));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[7] (.RN (i_rstn), .CK
       (i_clk), .D (n_132), .Q (ex_to_me_result[7]));
  NOR2X1 g4054__6783(.A (id_to_ex_imm[10]), .B (n_137), .Y (n_138));
  OAI2BB1X1 g4047__3680(.A0N (n_135), .A1N (n_130), .B0 (n_134), .Y
       (n_136));
  AOI22X1 g4033__1617(.A0 (n_140), .A1 (n_122), .B0 (n_139), .B1
       (ex_to_me_result[8]), .Y (n_133));
  OAI2BB1X1 g4025__2802(.A0N (id_to_ex_imm[7]), .A1N (n_120), .B0
       (n_127), .Y (n_132));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[6] (.RN (i_rstn), .CK
       (i_clk), .D (n_129), .Q (ex_to_me_result[6]));
  NOR2X1 g4059__1705(.A (id_to_ex_imm[9]), .B (n_130), .Y (n_131));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[4] (.RN (i_rstn), .CK
       (i_clk), .D (n_124), .Q (ex_to_me_result[4]));
  NOR2BX1 g4060__5122(.AN (n_130), .B (id_to_ex_imm[9]), .Y (n_137));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[5] (.RN (i_rstn), .CK
       (i_clk), .D (n_125), .Q (ex_to_me_result[5]));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[2] (.RN (i_rstn), .CK
       (i_clk), .D (n_123), .Q (ex_to_me_result[2]));
  DFFRHQX1 \u_execute_buffer_alu_result_reg[3] (.RN (i_rstn), .CK
       (i_clk), .D (n_126), .Q (ex_to_me_result[3]));
  OAI2BB1X1 g4022__8246(.A0N (id_to_ex_imm[6]), .A1N (n_113), .B0
       (n_119), .Y (n_129));
  OAI2BB1X1 g4048__7098(.A0N (n_135), .A1N (n_121), .B0 (n_134), .Y
       (n_128));
  AOI22X1 g4036__6131(.A0 (n_140), .A1 (n_118), .B0 (n_139), .B1
       (ex_to_me_result[7]), .Y (n_127));
  OAI2BB1X1 g4030__1881(.A0N (id_to_ex_imm[3]), .A1N (n_111), .B0
       (n_114), .Y (n_126));
  OAI2BB1X1 g4023__5115(.A0N (id_to_ex_imm[5]), .A1N (n_115), .B0
       (n_109), .Y (n_125));
  OAI2BB1X1 g4031__7482(.A0N (id_to_ex_imm[4]), .A1N (n_116), .B0
       (n_108), .Y (n_124));
  OAI2BB1X1 g4027__4733(.A0N (id_to_ex_imm[2]), .A1N (n_110), .B0
       (n_112), .Y (n_123));
  NOR2X1 g4061__6161(.A (id_to_ex_imm[8]), .B (n_121), .Y (n_122));
  NOR2BX1 g4063__9315(.AN (n_121), .B (id_to_ex_imm[8]), .Y (n_130));
  OAI2BB1X1 g4043__9945(.A0N (n_135), .A1N (n_117), .B0 (n_134), .Y
       (n_120));
  AOI22X1 g4034__2883(.A0 (n_140), .A1 (n_106), .B0 (n_139), .B1
       (ex_to_me_result[6]), .Y (n_119));
  NOR2X1 g4065__2346(.A (id_to_ex_imm[7]), .B (n_117), .Y (n_118));
  NOR2BX1 g4066__1666(.AN (n_117), .B (id_to_ex_imm[7]), .Y (n_121));
  OAI2BB1X1 g4042__7410(.A0N (n_101), .A1N (n_135), .B0 (n_134), .Y
       (n_116));
  OAI2BB1X1 g4041__6417(.A0N (n_135), .A1N (n_104), .B0 (n_134), .Y
       (n_115));
  AOI22X1 g4040__5477(.A0 (n_100), .A1 (n_140), .B0 (n_139), .B1
       (ex_to_me_result[3]), .Y (n_114));
  OAI2BB1X1 g4044__2398(.A0N (n_135), .A1N (n_107), .B0 (n_134), .Y
       (n_113));
  AOI22X1 g4035__5107(.A0 (n_96), .A1 (n_140), .B0 (n_139), .B1
       (ex_to_me_result[2]), .Y (n_112));
  OAI2BB1X1 g4050__6260(.A0N (n_99), .A1N (n_135), .B0 (n_134), .Y
       (n_111));
  OAI2BB1X1 g4049__4319(.A0N (n_95), .A1N (n_135), .B0 (n_134), .Y
       (n_110));
  AOI22X1 g4037__8428(.A0 (n_140), .A1 (n_105), .B0 (n_139), .B1
       (ex_to_me_result[5]), .Y (n_109));
  AOI22X1 g4038__5526(.A0 (n_102), .A1 (n_140), .B0 (n_139), .B1
       (ex_to_me_result[4]), .Y (n_108));
  NOR2BX1 g4071__6783(.AN (n_107), .B (id_to_ex_imm[6]), .Y (n_117));
  NOR2X1 g4068__3680(.A (id_to_ex_imm[6]), .B (n_107), .Y (n_106));
  OR2X2 g4053__1617(.A (id_to_ex_arith), .B (n_103), .Y (n_134));
  NOR2X1 g4073__2802(.A (id_to_ex_imm[5]), .B (n_104), .Y (n_105));
  NOR2BX1 g4074__1705(.AN (n_104), .B (id_to_ex_imm[5]), .Y (n_107));
  AND2X2 g4051__5122(.A (id_to_ex_arith), .B (n_135), .Y (n_140));
  INVX1 g4055(.A (n_135), .Y (n_103));
  NOR2X1 g4078__8246(.A (id_to_ex_imm[4]), .B (n_101), .Y (n_102));
  NOR2BX1 g4079__7098(.AN (n_101), .B (id_to_ex_imm[4]), .Y (n_104));
  AND3X2 g4056__6131(.A (id_to_ex_src_imm), .B (id_to_ex_rw), .C
       (n_97), .Y (n_135));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[3] (.RN (i_rstn), .CK (i_clk), .D
       (n_16), .SI (ex_to_if_pc_target[3]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[3]));
  NOR2X1 g4083__1881(.A (id_to_ex_imm[3]), .B (n_99), .Y (n_100));
  NOR2BX1 g4082__5115(.AN (n_99), .B (id_to_ex_imm[3]), .Y (n_101));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[5] (.RN (i_rstn), .CK (i_clk), .D
       (n_29), .SI (ex_to_if_pc_target[5]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[5]));
  XOR2XL g4052__7482(.A (n_93), .B (u_fetch_pc_value[10]), .Y (n_98));
  NOR2X1 g4062__4733(.A (id_to_ex_alu_op[0]), .B (id_to_ex_alu_op[1]),
       .Y (n_97));
  NOR2X1 g4086__6161(.A (id_to_ex_imm[2]), .B (n_95), .Y (n_96));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[7] (.RN (i_rstn), .CK (i_clk), .D
       (n_62), .SI (ex_to_if_pc_target[7]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[7]));
  NOR2BX1 g4087__9315(.AN (n_95), .B (id_to_ex_imm[2]), .Y (n_99));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[6] (.RN (i_rstn), .CK (i_clk), .D
       (n_43), .SI (ex_to_if_pc_target[6]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[6]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[4] (.RN (i_rstn), .CK (i_clk), .D
       (n_21), .SI (ex_to_if_pc_target[4]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[4]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[8] (.RN (i_rstn), .CK (i_clk), .D
       (n_90), .SI (ex_to_if_pc_target[8]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[8]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[2] (.RN (i_rstn), .CK (i_clk), .D
       (n_7), .SI (ex_to_if_pc_target[2]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[2]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[3] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[3]), .Q (ex_to_if_pc_target[3]));
  DFFQXL \u_decode_o_alu_op_buffer_2_reg[0] (.CK (i_clk), .D (n_92), .Q
       (id_to_ex_alu_op[0]));
  ADDHX1 g4057__9945(.A (u_fetch_pc_value[9]), .B (n_89), .CO (n_93),
       .S (n_94));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[5] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[5]), .Q (ex_to_if_pc_target[5]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[10] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[10]), .Q (ex_to_if_pc_target[10]));
  NOR2X1 g4096__2883(.A (id_to_ex_imm[0]), .B (id_to_ex_imm[1]), .Y
       (n_95));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[9] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[9]), .Q (ex_to_if_pc_target[9]));
  OAI32X1 g4070__2346(.A0 (if_to_id_instr[26]), .A1
       (if_to_id_instr[2]), .A2 (n_81), .B0 (n_86), .B1 (n_51), .Y
       (n_92));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[3] (.CK (i_clk), .D (n_91), .Q
       (id_to_ex_imm[3]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[6] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[6]), .Q (ex_to_if_pc_target[6]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[2] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[2]), .Q (ex_to_if_pc_target[2]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[4] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[4]), .Q (ex_to_if_pc_target[4]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[7] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[7]), .Q (ex_to_if_pc_target[7]));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[0] (.CK (i_clk), .D (n_88), .Q
       (id_to_ex_imm[0]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[8] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[8]), .Q (ex_to_if_pc_target[8]));
  DFFQXL \u_decode_o_imm_buffer_2_reg[10] (.CK (i_clk), .D (n_84), .Q
       (id_to_ex_imm[10]));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[5] (.CK (i_clk), .D (n_85), .Q
       (id_to_ex_imm[5]));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[9] (.CK (i_clk), .D (n_80), .Q
       (id_to_ex_imm[9]));
  OAI221X2 g4108__1666(.A0 (n_13), .A1 (n_87), .B0
       (if_to_id_instr[24]), .B1 (n_82), .C0 (n_78), .Y (n_91));
  ADDHX1 g4067__7410(.A (u_fetch_pc_value[8]), .B (n_61), .CO (n_89),
       .S (n_90));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[8] (.CK (i_clk), .D (n_64), .Q
       (id_to_ex_imm[8]));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[7] (.CK (i_clk), .D (n_66), .Q
       (id_to_ex_imm[7]));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[6] (.CK (i_clk), .D (n_68), .Q
       (id_to_ex_imm[6]));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[4] (.CK (i_clk), .D (n_65), .Q
       (id_to_ex_imm[4]));
  OAI221X2 g4111__6417(.A0 (n_83), .A1 (n_87), .B0 (n_86), .B1 (n_79),
       .C0 (n_76), .Y (n_88));
  OAI2BB1X1 g4117__5477(.A0N (if_to_id_instr[26]), .A1N (n_57), .B0
       (n_73), .Y (n_85));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[1] (.CK (i_clk), .D (n_71), .Q
       (id_to_ex_imm[1]));
  OAI221X1 g4115__2398(.A0 (if_to_id_instr[30]), .A1 (n_60), .B0
       (n_83), .B1 (n_82), .C0 (n_53), .Y (n_84));
  DFFHQX1 \u_decode_o_imm_buffer_2_reg[2] (.CK (i_clk), .D (n_77), .Q
       (id_to_ex_imm[2]));
  OR4X1 g4084__5107(.A (if_to_id_instr[13]), .B (if_to_id_instr[14]),
       .C (if_to_id_instr[25]), .D (n_59), .Y (n_81));
  OAI221X1 g4120__6260(.A0 (if_to_id_instr[30]), .A1 (n_46), .B0
       (n_70), .B1 (n_79), .C0 (n_63), .Y (n_80));
  AOI222X1 g4121__4319(.A0 (if_to_id_instr[11]), .A1 (n_75), .B0
       (if_to_id_instr[15]), .B1 (n_72), .C0 (if_to_id_instr[10]), .C1
       (n_74), .Y (n_78));
  OAI221X2 g4112__8428(.A0 (n_12), .A1 (n_87), .B0 (n_11), .B1 (n_69),
       .C0 (n_48), .Y (n_77));
  AOI222X1 g4126__5526(.A0 (if_to_id_instr[8]), .A1 (n_75), .B0
       (if_to_id_instr[21]), .B1 (n_49), .C0 (if_to_id_instr[7]), .C1
       (n_74), .Y (n_76));
  AOI22X1 g4128__6783(.A0 (if_to_id_instr[25]), .A1 (n_590), .B0
       (if_to_id_instr[17]), .B1 (n_72), .Y (n_73));
  OAI221X2 g4113__3680(.A0 (n_70), .A1 (n_87), .B0 (n_14), .B1 (n_69),
       .C0 (n_50), .Y (n_71));
  OAI2BB1X1 g4118__1617(.A0N (if_to_id_instr[26]), .A1N (n_590), .B0
       (n_54), .Y (n_68));
  OAI2BB1X1 g4116__2802(.A0N (if_to_id_instr[27]), .A1N (n_590), .B0
       (n_56), .Y (n_66));
  OAI221X1 g4114__1705(.A0 (if_to_id_instr[24]), .A1 (n_87), .B0
       (n_10), .B1 (n_69), .C0 (n_58), .Y (n_65));
  OAI2BB1X1 g4119__5122(.A0N (if_to_id_instr[28]), .A1N (n_590), .B0
       (n_55), .Y (n_64));
  NAND2X1 g4134__8246(.A (if_to_id_instr[29]), .B (n_590), .Y (n_63));
  ADDHX1 g4081__7098(.A (u_fetch_pc_value[7]), .B (n_42), .CO (n_61),
       .S (n_62));
  INVX1 g4146(.A (n_590), .Y (n_60));
  OR4X1 g4105__6131(.A (if_to_id_instr[28]), .B (if_to_id_instr[29]),
       .C (if_to_id_instr[30]), .D (n_47), .Y (n_59));
  DFFHQX1 \u_decode_o_alu_op_buffer_2_reg[1] (.CK (i_clk), .D (n_52),
       .Q (id_to_ex_alu_op[1]));
  AOI22X1 g4129__1881(.A0 (if_to_id_instr[25]), .A1 (n_57), .B0
       (if_to_id_instr[16]), .B1 (n_72), .Y (n_58));
  AOI22X1 g4130__5115(.A0 (if_to_id_instr[28]), .A1 (n_57), .B0
       (if_to_id_instr[19]), .B1 (n_72), .Y (n_56));
  AOI22X1 g4131__7482(.A0 (if_to_id_instr[29]), .A1 (n_57), .B0
       (if_to_id_instr[20]), .B1 (n_72), .Y (n_55));
  DFFRHQX1 u_execute_buffer_we_reg(.RN (i_rstn), .CK (i_clk), .D
       (id_to_ex_rw), .Q (ex_to_me_we));
  AOI22X1 g4127__4733(.A0 (if_to_id_instr[27]), .A1 (n_57), .B0
       (if_to_id_instr[18]), .B1 (n_72), .Y (n_54));
  INVX1 g4144(.A (n_69), .Y (n_74));
  AOI22X1 g4138__9315(.A0 (if_to_id_instr[7]), .A1 (n_75), .B0
       (if_to_id_instr[22]), .B1 (n_72), .Y (n_53));
  INVX1 g4136(.A (n_51), .Y (n_52));
  INVX2 g4140(.A (id_to_ex_rw), .Y (n_139));
  DFFRX2 u_execute_buffer_pc_transfer_reg(.RN (i_rstn), .CK (i_clk), .D
       (n_41), .Q (ex_to_if_pc_transfer), .QN (UNCONNECTED));
  AOI222X1 g4122__9945(.A0 (if_to_id_instr[9]), .A1 (n_75), .B0
       (if_to_id_instr[22]), .B1 (n_49), .C0 (if_to_id_instr[13]), .C1
       (n_72), .Y (n_50));
  AOI222X1 g4125__2883(.A0 (if_to_id_instr[10]), .A1 (n_75), .B0
       (if_to_id_instr[23]), .B1 (n_49), .C0 (if_to_id_instr[14]), .C1
       (n_72), .Y (n_48));
  DFFHQX1 u_decode_o_arith_buffer_2_reg(.CK (i_clk), .D (n_40), .Q
       (id_to_ex_arith));
  NAND2X2 g4148__2346(.A (if_to_id_instr[5]), .B (n_591), .Y (n_69));
  OR4X1 g4137__1666(.A (if_to_id_instr[31]), .B (if_to_id_instr[12]),
       .C (if_to_id_instr[27]), .D (n_35), .Y (n_47));
  NAND3BX2 g4139__7410(.AN (n_39), .B (if_to_id_instr[14]), .C
       (if_to_id_instr[13]), .Y (n_51));
  INVX1 g4145(.A (n_57), .Y (n_46));
  DFFHQX1 u_decode_o_rw_buffer_2_reg(.CK (i_clk), .D (n_38), .Q
       (id_to_ex_rw));
  ADDHX1 g4098__6417(.A (u_fetch_pc_value[6]), .B (n_28), .CO (n_42),
       .S (n_43));
  OR2X1 g4147__5477(.A (id_to_ex_jump), .B (u_execute_branch_taken), .Y
       (n_41));
  OR2X1 g4149__2398(.A (n_49), .B (n_75), .Y (n_57));
  INVX1 g4157(.A (n_39), .Y (n_40));
  INVX1 g4151(.A (n_72), .Y (n_79));
  DFFHQX1 u_decode_o_src_imm_buffer_2_reg(.CK (i_clk), .D (n_31), .Q
       (id_to_ex_src_imm));
  INVX1 g4158(.A (n_49), .Y (n_82));
  AND2X2 g4155__6260(.A (if_to_id_instr[2]), .B (n_34), .Y (n_72));
  AND2X1 g4159__4319(.A (n_37), .B (n_32), .Y (n_38));
  DFFRHQX1 u_execute_branch_taken_reg(.RN (i_rstn), .CK (i_clk), .D
       (id_to_ex_branch), .Q (u_execute_branch_taken));
  NAND2X1 g4161__8428(.A (if_to_id_instr[4]), .B (n_37), .Y (n_39));
  DFFQXL u_decode_o_jump_buffer_2_reg(.CK (i_clk), .D (n_36), .Q
       (id_to_ex_jump));
  AND2X1 g4162__5526(.A (n_36), .B (if_to_id_instr[3]), .Y (n_49));
  INVX1 g4163(.A (n_34), .Y (n_35));
  DFFHQX1 u_decode_o_branch_buffer_2_reg(.CK (i_clk), .D (n_75), .Q
       (id_to_ex_branch));
  NOR2X1 g4166__6783(.A (n_32), .B (n_30), .Y (n_34));
  INVX1 g4168(.A (n_87), .Y (n_31));
  NOR2X1 g4167__3680(.A (if_to_id_instr[2]), .B (n_30), .Y (n_37));
  ADDHX1 g4132__1617(.A (u_fetch_pc_value[5]), .B (n_20), .CO (n_28),
       .S (n_29));
  NOR2X1 g4169__2802(.A (i_rstn), .B (n_26), .Y (n_36));
  OR2X1 g4171__1705(.A (n_27), .B (n_24), .Y (n_87));
  AND3X1 g4170__5122(.A (n_23), .B (n_22), .C (n_25), .Y (n_75));
  OR2X1 g4172__8246(.A (if_to_id_instr[6]), .B (n_27), .Y (n_30));
  NAND3BX1 g4173__7098(.AN (n_19), .B (if_to_id_instr[2]), .C (n_25),
       .Y (n_26));
  MXI2XL g4174__6131(.A (n_25), .B (n_17), .S0 (n_23), .Y (n_24));
  INVX1 g4175(.A (n_22), .Y (n_27));
  ADDHX1 g4165__1881(.A (u_fetch_pc_value[4]), .B (n_15), .CO (n_20),
       .S (n_21));
  NOR3X1 g4176__5115(.A (if_to_id_instr[3]), .B (i_rstn), .C (n_19), .Y
       (n_22));
  NOR2X1 g4178__7482(.A (if_to_id_instr[4]), .B (n_18), .Y (n_25));
  NAND2X1 g4179__4733(.A (if_to_id_instr[5]), .B (if_to_id_instr[6]),
       .Y (n_18));
  NAND2X1 g4180__6161(.A (if_to_id_instr[0]), .B (if_to_id_instr[1]),
       .Y (n_19));
  NOR2X1 g4181__9315(.A (if_to_id_instr[5]), .B (if_to_id_instr[6]), .Y
       (n_17));
  NAND2X1 g4182__9945(.A (if_to_id_instr[4]), .B (if_to_id_instr[5]),
       .Y (n_32));
  ADDHX1 g4177__2883(.A (u_fetch_pc_value[2]), .B
       (u_fetch_pc_value[3]), .CO (n_15), .S (n_16));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[0] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[0]), .Q (if_to_id_instr[0]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[31] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[31]), .Q (if_to_id_instr[31]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[18] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[18]), .Q (if_to_id_instr[18]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[15] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[15]), .Q (if_to_id_instr[15]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[16] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[16]), .Q (if_to_id_instr[16]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[19] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[19]), .Q (if_to_id_instr[19]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[17] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[17]), .Q (if_to_id_instr[17]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[1] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[1]), .Q (if_to_id_instr[1]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[10] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[10]), .Q (if_to_id_instr[10]));
  DFFRX1 \u_fetch_InstructionBuffer_reg[24] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[24]), .Q (UNCONNECTED0), .QN (if_to_id_instr[24]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[25] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[25]), .Q (if_to_id_instr[25]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[6] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[6]), .Q (if_to_id_instr[6]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[4] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[4]), .Q (if_to_id_instr[4]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[7] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[7]), .Q (if_to_id_instr[7]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[3] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[3]), .Q (if_to_id_instr[3]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[14] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[14]), .Q (if_to_id_instr[14]));
  DFFRX1 \u_fetch_InstructionBuffer_reg[30] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[30]), .Q (UNCONNECTED1), .QN (if_to_id_instr[30]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[26] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[26]), .Q (if_to_id_instr[26]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[29] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[29]), .Q (if_to_id_instr[29]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[28] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[28]), .Q (if_to_id_instr[28]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[13] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[13]), .Q (if_to_id_instr[13]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[27] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[27]), .Q (if_to_id_instr[27]));
  DFFRHQX1 \u_fetch_InstructionBuffer_reg[5] (.RN (n_9), .CK (i_clk),
       .D (i_imem_read[5]), .Q (if_to_id_instr[5]));
  INVX1 g4241(.A (u_fetch_pc_value[2]), .Y (n_7));
  INVXL g4237(.A (i_rstn), .Y (n_9));
  CLKBUFX20 drc_bufs4336(.A (u_fetch_pc_value[2]), .Y (o_imem_addr[0]));
  CLKBUFX20 drc_bufs4341(.A (u_fetch_pc_value[9]), .Y (o_imem_addr[7]));
  CLKBUFX20 drc_bufs4346(.A (u_fetch_pc_value[10]), .Y
       (o_imem_addr[8]));
  CLKBUFX20 drc_bufs(.A (u_fetch_pc_value[5]), .Y (o_imem_addr[3]));
  CLKBUFX20 drc_bufs4351(.A (u_fetch_pc_value[8]), .Y (o_imem_addr[6]));
  CLKBUFX20 drc_bufs4354(.A (u_fetch_pc_value[6]), .Y (o_imem_addr[4]));
  CLKBUFX20 drc_bufs4357(.A (u_fetch_pc_value[7]), .Y (o_imem_addr[5]));
  CLKBUFX20 drc_bufs4360(.A (u_fetch_pc_value[4]), .Y (o_imem_addr[2]));
  CLKBUFX20 drc_bufs4363(.A (u_fetch_pc_value[3]), .Y (o_imem_addr[1]));
  CLKBUFX20 drc_bufs4366(.A (n_588), .Y (o_dmem_addr[7]));
  CLKBUFX20 drc_bufs4369(.A (n_586), .Y (o_dmem_addr[3]));
  CLKBUFX20 drc_bufs4372(.A (n_589), .Y (o_dmem_addr[2]));
  CLKBUFX20 drc_bufs4375(.A (n_584), .Y (o_dmem_addr[8]));
  CLKBUFX20 drc_bufs4378(.A (n_583), .Y (o_dmem_we));
  CLKBUFX20 drc_bufs4381(.A (n_582), .Y (o_dmem_addr[0]));
  CLKBUFX20 drc_bufs4384(.A (n_581), .Y (o_dmem_addr[4]));
  CLKBUFX20 drc_bufs4387(.A (n_585), .Y (o_dmem_addr[1]));
  CLKBUFX20 drc_bufs4390(.A (n_580), .Y (o_dmem_addr[5]));
  CLKBUFX20 drc_bufs4393(.A (n_579), .Y (o_dmem_en));
  CLKBUFX20 drc_bufs4396(.A (n_587), .Y (o_dmem_addr[6]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[10] (.RN (i_rstn), .CK (i_clk), .D
       (n_98), .SI (ex_to_if_pc_target[10]), .SE
       (ex_to_if_pc_transfer), .Q (u_fetch_pc_value[10]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[9] (.RN (i_rstn), .CK (i_clk), .D
       (n_94), .SI (ex_to_if_pc_target[9]), .SE (ex_to_if_pc_transfer),
       .Q (u_fetch_pc_value[9]));
  DFFRX1 \u_fetch_InstructionBuffer_reg[8] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[8]), .Q (if_to_id_instr[8]), .QN (n_14));
  DFFRX1 \u_fetch_InstructionBuffer_reg[23] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[23]), .Q (if_to_id_instr[23]), .QN (n_13));
  DFFRX1 \u_fetch_InstructionBuffer_reg[22] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[22]), .Q (if_to_id_instr[22]), .QN (n_12));
  DFFRX1 \u_fetch_InstructionBuffer_reg[21] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[21]), .Q (if_to_id_instr[21]), .QN (n_70));
  DFFRX1 \u_fetch_InstructionBuffer_reg[9] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[9]), .Q (if_to_id_instr[9]), .QN (n_11));
  DFFRX1 \u_fetch_InstructionBuffer_reg[11] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[11]), .Q (if_to_id_instr[11]), .QN (n_10));
  DFFRX1 \u_fetch_InstructionBuffer_reg[2] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[2]), .Q (if_to_id_instr[2]), .QN (n_23));
  DFFRX1 \u_fetch_InstructionBuffer_reg[20] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[20]), .Q (if_to_id_instr[20]), .QN (n_83));
  DFFRX1 \u_fetch_InstructionBuffer_reg[12] (.RN (n_9), .CK (i_clk), .D
       (i_imem_read[12]), .Q (if_to_id_instr[12]), .QN (n_86));
  DFFRHQX1 u_memory_o_dmem_en_reg(.RN (i_rstn), .CK (i_clk), .D (1'b1),
       .Q (n_579));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[5] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[7]), .Q (n_580));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[4] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[6]), .Q (n_581));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[0] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[2]), .Q (n_582));
  DFFRHQX1 u_memory_o_dmem_we_reg(.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_we), .Q (n_583));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[8] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[10]), .Q (n_584));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[1] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[3]), .Q (n_585));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[3] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[5]), .Q (n_586));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[6] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[8]), .Q (n_587));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[7] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[9]), .Q (n_588));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[2] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[4]), .Q (n_589));
  NAND2BX2 g2(.AN (n_591), .B (n_87), .Y (n_590));
  NOR2BX1 g4704(.AN (n_37), .B (if_to_id_instr[4]), .Y (n_591));
endmodule

