
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 27 2024 00:00:19 EST (Nov 27 2024 05:00:19 UTC)

// Verification Directory fv/riscv_core 

module riscv_core(i_rstn, i_clk, o_imem_en, o_imem_addr, i_imem_read,
     o_dmem_en, o_dmem_we, o_dmem_addr, i_dmem_read, o_dmem_write,
     i_scan_en, i_test_mode, i_tdi, o_tdo);
  input i_rstn, i_clk, i_scan_en, i_test_mode, i_tdi;
  input [31:0] i_imem_read, i_dmem_read;
  output o_imem_en, o_dmem_en, o_dmem_we, o_tdo;
  output [8:0] o_imem_addr, o_dmem_addr;
  output [31:0] o_dmem_write;
  wire i_rstn, i_clk, i_scan_en, i_test_mode, i_tdi;
  wire [31:0] i_imem_read, i_dmem_read;
  wire o_imem_en, o_dmem_en, o_dmem_we, o_tdo;
  wire [8:0] o_imem_addr, o_dmem_addr;
  wire [31:0] o_dmem_write;
  wire [31:0] ex_to_if_pc_target;
  wire [31:0] if_to_id_instr;
  wire [2:0] id_to_ex_alu_op;
  wire [31:0] id_to_ex_imm;
  wire [31:0] ex_to_me_result;
  wire ex_to_if_pc_transfer, ex_to_me_we, id_to_ex_arith,
       id_to_ex_branch, id_to_ex_jump, id_to_ex_rw, id_to_ex_src_imm,
       n_527;
  wire n_531, n_532, n_534, n_539, n_540, n_541, n_542, n_543;
  wire n_544, n_545, n_546, n_547, n_548, n_553, n_554, n_559;
  wire n_560, n_567, n_568, n_572, n_577, n_578, n_583, n_584;
  wire n_589, n_590, n_595, n_596, n_601, n_602, n_607, n_608;
  wire n_613, n_614, n_616, n_617, n_618, n_619, n_620, n_621;
  wire n_622, n_623, n_624, n_625, n_626, n_627, n_628, n_629;
  wire n_630, n_631, n_632, u_decode_n_700, u_decode_n_703,
       u_decode_n_706, u_decode_n_709, u_decode_n_712;
  wire u_decode_n_715, u_decode_n_718, u_decode_n_721, u_decode_n_724,
       u_decode_n_727, u_decode_n_730, u_decode_n_733, u_decode_n_736;
  wire u_decode_n_739, u_decode_n_742, u_decode_n_772, u_decode_n_775,
       u_decode_n_778, u_decode_n_2786, u_decode_n_2788,
       u_decode_n_2789;
  wire u_decode_n_2804, u_decode_n_2808, u_decode_n_2810,
       u_decode_n_2811, u_decode_n_2813, u_decode_n_2816,
       u_decode_n_2818, u_decode_n_2822;
  wire u_decode_n_2848, u_decode_n_2855, u_decode_n_2879,
       u_decode_n_2889, u_decode_n_2895, u_decode_n_2898,
       u_decode_n_2903, u_decode_n_2904;
  wire u_decode_n_2911, u_decode_n_2912, u_decode_n_2913,
       u_decode_n_2918, u_decode_n_2919, u_decode_n_2922,
       u_decode_n_2925, u_decode_n_2928;
  wire u_decode_n_2937, u_decode_n_2938, u_decode_n_2939,
       u_decode_n_2940, u_decode_n_2949, u_decode_n_2950,
       u_decode_n_2951, u_decode_n_2952;
  wire u_decode_n_2961, u_decode_n_2962, u_decode_n_2963,
       u_decode_n_2964, u_decode_n_2973, u_decode_n_2974,
       u_decode_n_2975, u_decode_n_2976;
  wire u_decode_n_2985, u_decode_n_2986, u_decode_n_2987,
       u_decode_n_2988, u_decode_n_3013, u_decode_n_3014,
       u_decode_n_3015, u_decode_n_3016;
  wire u_decode_n_3017, u_decode_n_3018, u_decode_n_3019,
       u_decode_n_3020, u_decode_n_3021, u_decode_n_3022,
       u_decode_n_3023, u_decode_n_3024;
  wire u_decode_n_3037, u_decode_n_3038, u_decode_n_3039,
       u_decode_n_3040, u_decode_n_3041, u_decode_n_3042,
       u_decode_n_3055, u_decode_n_3056;
  wire u_decode_n_3057, u_decode_n_3058, u_decode_n_3059,
       u_decode_n_3060, u_decode_n_3077, u_decode_n_3078,
       u_decode_n_3079, u_decode_n_3080;
  wire u_decode_n_3081, u_decode_n_3082, u_decode_n_3083,
       u_decode_n_3084, u_decode_n_3101, u_decode_n_3102,
       u_decode_n_3103, u_decode_n_3104;
  wire u_decode_n_3105, u_decode_n_3106, u_decode_n_3107,
       u_decode_n_3108, u_decode_n_3125, u_decode_n_3126,
       u_decode_n_3127, u_decode_n_3128;
  wire u_decode_n_3129, u_decode_n_3130, u_decode_n_3131,
       u_decode_n_3132, u_decode_n_3149, u_decode_n_3150,
       u_decode_n_3151, u_decode_n_3152;
  wire u_decode_n_3153, u_decode_n_3154, u_decode_n_3155,
       u_decode_n_3156, u_decode_n_3161, u_decode_n_3162,
       u_execute_branch_taken, u_execute_n_976;
  wire u_execute_n_978, u_execute_n_980, u_execute_n_982,
       u_execute_n_984, u_execute_n_986, u_execute_n_988,
       u_execute_n_990, u_execute_n_992;
  wire u_execute_n_2541, u_execute_n_2543, u_execute_n_2546,
       u_execute_n_2552, u_execute_n_2555, u_execute_n_2558,
       u_execute_n_2562, u_execute_n_2570;
  wire u_execute_n_2578, u_execute_n_2586, u_execute_n_2594,
       u_execute_n_2602, u_execute_n_2610, u_execute_n_2626,
       u_execute_n_2627, u_execute_n_2628;
  wire u_execute_n_2629, u_execute_n_2630, u_execute_n_2631,
       u_execute_n_2632, u_execute_n_2633, u_execute_n_2634,
       u_execute_n_2635, u_execute_n_2640;
  wire u_execute_n_2641, u_execute_n_2644, u_execute_n_2647,
       u_execute_n_2658, u_execute_n_2659, u_execute_n_2660,
       u_execute_n_2661, u_execute_n_2662;
  wire u_execute_n_2673, u_execute_n_2674, u_execute_n_2675,
       u_execute_n_2676, u_execute_n_2677, u_execute_n_2680,
       u_execute_n_2683, u_execute_n_2694;
  wire u_execute_n_2695, u_execute_n_2696, u_execute_n_2697,
       u_execute_n_2698, u_execute_n_2701, u_execute_n_2712,
       u_execute_n_2713, u_execute_n_2714;
  wire u_execute_n_2715, u_execute_n_2716, u_execute_n_2719,
       u_execute_n_2730, u_execute_n_2731, u_execute_n_2732,
       u_execute_n_2733, u_execute_n_2734;
  wire u_execute_n_2737, u_execute_n_2748, u_execute_n_2749,
       u_execute_n_2750, u_execute_n_2751, u_execute_n_2752,
       u_execute_n_2755, u_execute_n_2766;
  wire u_execute_n_2767, u_execute_n_2768, u_execute_n_2769,
       u_execute_n_2770, u_execute_n_2773, u_execute_n_2784,
       u_execute_n_2785, u_execute_n_2786;
  wire u_execute_n_2787, u_execute_n_2788, u_execute_n_2799,
       u_execute_n_2800, u_execute_n_2801, u_execute_n_2802,
       u_execute_n_2803, u_fetch_u_add_n_79;
  wire u_fetch_u_add_n_81, u_fetch_u_add_n_83, u_fetch_u_add_n_85,
       u_fetch_u_add_n_87, u_fetch_u_add_n_89, u_fetch_u_add_n_91,
       u_fetch_u_add_n_93, u_fetch_u_add_n_95;
  assign o_tdo = 1'b0;
  assign o_dmem_write[0] = 1'b0;
  assign o_dmem_write[1] = 1'b0;
  assign o_dmem_write[2] = 1'b0;
  assign o_dmem_write[3] = 1'b0;
  assign o_dmem_write[4] = 1'b0;
  assign o_dmem_write[5] = 1'b0;
  assign o_dmem_write[6] = 1'b0;
  assign o_dmem_write[7] = 1'b0;
  assign o_dmem_write[8] = 1'b0;
  assign o_dmem_write[9] = 1'b0;
  assign o_dmem_write[10] = 1'b0;
  assign o_dmem_write[11] = 1'b0;
  assign o_dmem_write[12] = 1'b0;
  assign o_dmem_write[13] = 1'b0;
  assign o_dmem_write[14] = 1'b0;
  assign o_dmem_write[15] = 1'b0;
  assign o_dmem_write[16] = 1'b0;
  assign o_dmem_write[17] = 1'b0;
  assign o_dmem_write[18] = 1'b0;
  assign o_dmem_write[19] = 1'b0;
  assign o_dmem_write[20] = 1'b0;
  assign o_dmem_write[21] = 1'b0;
  assign o_dmem_write[22] = 1'b0;
  assign o_dmem_write[23] = 1'b0;
  assign o_dmem_write[24] = 1'b0;
  assign o_dmem_write[25] = 1'b0;
  assign o_dmem_write[26] = 1'b0;
  assign o_dmem_write[27] = 1'b0;
  assign o_dmem_write[28] = 1'b0;
  assign o_dmem_write[29] = 1'b0;
  assign o_dmem_write[30] = 1'b0;
  assign o_dmem_write[31] = 1'b0;
  assign o_imem_en = 1'b1;
  or g596 (n_532, n_531, wc);
  not gc (wc, o_imem_addr[3]);
  or g655 (n_543, n_532, wc0);
  not gc0 (wc0, o_imem_addr[4]);
  nand g708 (u_fetch_u_add_n_95, n_595, n_596);
  nand g709 (u_fetch_u_add_n_93, n_601, n_602);
  nand g710 (u_fetch_u_add_n_89, n_613, n_614);
  or g711 (n_595, wc1, ex_to_if_pc_transfer);
  not gc1 (wc1, n_539);
  nand g712 (u_fetch_u_add_n_91, n_583, n_584);
  nand g713 (u_fetch_u_add_n_87, n_607, n_608);
  or g714 (n_613, wc2, ex_to_if_pc_transfer);
  not gc2 (wc2, n_544);
  or g715 (n_601, wc3, ex_to_if_pc_transfer);
  not gc3 (wc3, n_541);
  or g716 (n_607, wc4, ex_to_if_pc_transfer);
  not gc4 (wc4, n_545);
  nand g717 (n_617, n_540, o_imem_addr[7]);
  or g718 (n_618, n_540, o_imem_addr[7]);
  nand g719 (n_541, n_617, n_618);
  nand g720 (n_619, n_543, o_imem_addr[5]);
  or g721 (n_620, n_543, o_imem_addr[5]);
  nand g722 (n_544, n_619, n_620);
  nand g723 (n_621, n_534, o_imem_addr[8]);
  or g724 (n_622, n_534, o_imem_addr[8]);
  nand g725 (n_539, n_621, n_622);
  nand g726 (u_fetch_u_add_n_85, n_589, n_590);
  or g727 (n_583, wc5, ex_to_if_pc_transfer);
  not gc5 (wc5, n_542);
  or g728 (n_589, wc6, ex_to_if_pc_transfer);
  not gc6 (wc6, n_546);
  or g729 (n_540, n_616, wc7);
  not gc7 (wc7, o_imem_addr[6]);
  nand g730 (n_623, n_532, o_imem_addr[4]);
  or g731 (n_624, n_532, o_imem_addr[4]);
  nand g732 (n_545, n_623, n_624);
  nand g733 (u_fetch_u_add_n_83, n_577, n_578);
  or g734 (n_625, n_616, o_imem_addr[6]);
  nand g735 (n_626, n_616, o_imem_addr[6]);
  nand g736 (n_542, n_625, n_626);
  or g737 (n_534, n_572, n_616);
  or g738 (n_577, wc8, ex_to_if_pc_transfer);
  not gc8 (wc8, n_547);
  nand g739 (n_627, n_531, o_imem_addr[3]);
  or g740 (n_628, n_531, o_imem_addr[3]);
  nand g741 (n_546, n_627, n_628);
  or g742 (n_616, n_531, n_568);
  nand g743 (u_fetch_u_add_n_81, n_559, n_560);
  or g744 (n_531, n_527, wc9);
  not gc9 (wc9, o_imem_addr[2]);
  or g745 (n_568, n_567, wc10);
  not gc10 (wc10, o_imem_addr[3]);
  nand g746 (u_fetch_u_add_n_79, n_553, n_554);
  or g747 (n_559, wc11, ex_to_if_pc_transfer);
  not gc11 (wc11, n_548);
  or g748 (n_629, n_527, o_imem_addr[2]);
  nand g749 (n_630, n_527, o_imem_addr[2]);
  nand g750 (n_547, n_629, n_630);
  or g751 (n_553, ex_to_if_pc_transfer, o_imem_addr[0]);
  or g752 (n_631, wc12, o_imem_addr[0]);
  not gc12 (wc12, o_imem_addr[1]);
  or g753 (n_632, o_imem_addr[1], wc13);
  not gc13 (wc13, o_imem_addr[0]);
  nand g754 (n_548, n_631, n_632);
  nand g755 (n_554, ex_to_if_pc_transfer, ex_to_if_pc_target[2]);
  nand g756 (n_578, ex_to_if_pc_transfer, ex_to_if_pc_target[4]);
  nand g757 (n_584, ex_to_if_pc_transfer, ex_to_if_pc_target[8]);
  nand g758 (n_590, ex_to_if_pc_transfer, ex_to_if_pc_target[5]);
  nand g759 (n_596, ex_to_if_pc_transfer, ex_to_if_pc_target[10]);
  nand g760 (n_602, ex_to_if_pc_transfer, ex_to_if_pc_target[9]);
  nand g761 (n_608, ex_to_if_pc_transfer, ex_to_if_pc_target[6]);
  nand g762 (n_614, ex_to_if_pc_transfer, ex_to_if_pc_target[7]);
  nand g763 (n_560, ex_to_if_pc_transfer, ex_to_if_pc_target[3]);
  nand g764 (n_567, o_imem_addr[5], o_imem_addr[4]);
  nand g765 (n_572, o_imem_addr[7], o_imem_addr[6]);
  nand g766 (n_527, o_imem_addr[1], o_imem_addr[0]);
  nand u_decode_g1931 (u_decode_n_700, u_decode_n_3023,
       u_decode_n_3024);
  or u_decode_g1932 (u_decode_n_3023, u_decode_n_3022,
       if_to_id_instr[2]);
  or u_decode_g1933 (u_decode_n_3022, u_decode_n_3021,
       if_to_id_instr[13]);
  or u_decode_g1934 (u_decode_n_3021, u_decode_n_3020,
       if_to_id_instr[14]);
  or u_decode_g1935 (u_decode_n_3020, u_decode_n_3019,
       if_to_id_instr[25]);
  or u_decode_g1936 (u_decode_n_3019, u_decode_n_3018,
       if_to_id_instr[26]);
  or u_decode_g1937 (u_decode_n_3018, u_decode_n_3017,
       if_to_id_instr[27]);
  or u_decode_g1938 (u_decode_n_715, u_decode_n_3083, u_decode_n_3084);
  or u_decode_g1939 (u_decode_n_721, u_decode_n_3155, u_decode_n_3156);
  or u_decode_g1940 (u_decode_n_736, wc14, u_decode_n_2940);
  not gc14 (wc14, u_decode_n_2939);
  or u_decode_g1941 (u_decode_n_730, wc15, u_decode_n_2964);
  not gc15 (wc15, u_decode_n_2963);
  or u_decode_g1942 (u_decode_n_733, wc16, u_decode_n_2988);
  not gc16 (wc16, u_decode_n_2987);
  or u_decode_g1943 (u_decode_n_3017, u_decode_n_3016,
       if_to_id_instr[28]);
  or u_decode_g1944 (u_decode_n_739, wc17, u_decode_n_2976);
  not gc17 (wc17, u_decode_n_2975);
  or u_decode_g1945 (u_decode_n_712, u_decode_n_3131, u_decode_n_3132);
  or u_decode_g1946 (u_decode_n_724, u_decode_n_3059, u_decode_n_3060);
  nand u_decode_g1947 (u_decode_n_2964, u_decode_n_2961,
       u_decode_n_2962);
  or u_decode_g1948 (u_decode_n_3156, wc18, u_decode_n_3154);
  not gc18 (wc18, u_decode_n_3153);
  nand u_decode_g1949 (u_decode_n_2988, u_decode_n_2985,
       u_decode_n_2986);
  nand u_decode_g1950 (u_decode_n_2940, u_decode_n_2937,
       u_decode_n_2938);
  nand u_decode_g1951 (u_decode_n_3060, u_decode_n_3057,
       u_decode_n_3058);
  or u_decode_g1952 (u_decode_n_3016, u_decode_n_3015,
       if_to_id_instr[29]);
  or u_decode_g1953 (u_decode_n_718, u_decode_n_3107, u_decode_n_3108);
  or u_decode_g1954 (u_decode_n_3084, wc19, u_decode_n_3082);
  not gc19 (wc19, u_decode_n_3081);
  or u_decode_g1955 (u_decode_n_727, wc20, u_decode_n_2952);
  not gc20 (wc20, u_decode_n_2951);
  or u_decode_g1956 (u_decode_n_3132, wc21, u_decode_n_3130);
  not gc21 (wc21, u_decode_n_3129);
  nand u_decode_g1957 (u_decode_n_2976, u_decode_n_2973,
       u_decode_n_2974);
  or u_decode_g1958 (u_decode_n_742, u_decode_n_3041, u_decode_n_3042);
  nand u_decode_g1959 (u_decode_n_3130, u_decode_n_3125,
       u_decode_n_3126);
  nand u_decode_g1960 (u_decode_n_2986, u_decode_n_2848,
       if_to_id_instr[28]);
  nand u_decode_g1961 (u_decode_n_3131, u_decode_n_3127,
       u_decode_n_3128);
  or u_decode_g1962 (u_decode_n_3015, u_decode_n_3014, wc22);
  not gc22 (wc22, if_to_id_instr[30]);
  or u_decode_g1963 (u_decode_n_3108, wc23, u_decode_n_3106);
  not gc23 (wc23, u_decode_n_3105);
  nand u_decode_g1964 (u_decode_n_3107, u_decode_n_3103,
       u_decode_n_3104);
  nand u_decode_g1965 (u_decode_n_2973, u_decode_n_2848,
       if_to_id_instr[30]);
  nand u_decode_g1966 (u_decode_n_3154, u_decode_n_3149,
       u_decode_n_3150);
  nand u_decode_g1967 (u_decode_n_2937, u_decode_n_2848,
       if_to_id_instr[29]);
  nand u_decode_g1968 (u_decode_n_3155, u_decode_n_3151,
       u_decode_n_3152);
  nand u_decode_g1969 (u_decode_n_3083, u_decode_n_3079,
       u_decode_n_3080);
  nand u_decode_g1970 (u_decode_n_3082, u_decode_n_3077,
       u_decode_n_3078);
  nand u_decode_g1971 (u_decode_n_2962, u_decode_n_2848,
       if_to_id_instr[27]);
  or u_decode_g1972 (u_decode_n_3024, u_decode_n_2879, wc24);
  not gc24 (wc24, if_to_id_instr[12]);
  nand u_decode_g1973 (u_decode_n_2952, u_decode_n_2949,
       u_decode_n_2950);
  nand u_decode_g1974 (u_decode_n_2951, u_decode_n_2848,
       if_to_id_instr[26]);
  nand u_decode_g1975 (u_decode_n_3059, u_decode_n_3055,
       u_decode_n_3056);
  nand u_decode_g1976 (u_decode_n_3058, u_decode_n_2848,
       if_to_id_instr[25]);
  nand u_decode_g1977 (u_decode_n_3041, u_decode_n_3037,
       u_decode_n_3038);
  nand u_decode_g1978 (u_decode_n_3042, u_decode_n_3039,
       u_decode_n_3040);
  or u_decode_g1979 (u_decode_n_3055, u_decode_n_2813, wc25);
  not gc25 (wc25, if_to_id_instr[11]);
  nand u_decode_g1980 (u_decode_n_3040, u_decode_n_2855,
       if_to_id_instr[30]);
  or u_decode_g1981 (u_decode_n_3039, u_decode_n_2811, wc26);
  not gc26 (wc26, if_to_id_instr[20]);
  or u_decode_g1982 (u_decode_n_3038, u_decode_n_2818, wc27);
  not gc27 (wc27, if_to_id_instr[22]);
  or u_decode_g1983 (u_decode_n_3057, u_decode_n_2818, wc28);
  not gc28 (wc28, if_to_id_instr[16]);
  or u_decode_g1984 (u_decode_n_3077, u_decode_n_2811, wc29);
  not gc29 (wc29, if_to_id_instr[22]);
  nand u_decode_g1985 (u_decode_n_2939, u_decode_n_2855,
       if_to_id_instr[28]);
  or u_decode_g1986 (u_decode_n_3079, u_decode_n_2818, wc30);
  not gc30 (wc30, if_to_id_instr[13]);
  or u_decode_g1987 (u_decode_n_2938, u_decode_n_2818, wc31);
  not gc31 (wc31, if_to_id_instr[20]);
  or u_decode_g1988 (u_decode_n_3081, u_decode_n_2813, wc32);
  not gc32 (wc32, if_to_id_instr[8]);
  or u_decode_g1989 (u_decode_n_2879, u_decode_n_2928, wc33);
  not gc33 (wc33, if_to_id_instr[13]);
  not u_decode_g1990 (u_decode_n_703, u_decode_n_2879);
  or u_decode_g1991 (u_decode_n_3103, u_decode_n_2818, wc34);
  not gc34 (wc34, if_to_id_instr[14]);
  or u_decode_g1992 (u_decode_n_3104, u_decode_n_2811, wc35);
  not gc35 (wc35, if_to_id_instr[23]);
  or u_decode_g1993 (u_decode_n_3105, u_decode_n_2813, wc36);
  not gc36 (wc36, if_to_id_instr[9]);
  nand u_decode_g1994 (u_decode_n_2963, u_decode_n_2855,
       if_to_id_instr[26]);
  or u_decode_g1995 (u_decode_n_3125, u_decode_n_2818, wc37);
  not gc37 (wc37, if_to_id_instr[12]);
  or u_decode_g1996 (u_decode_n_3014, u_decode_n_3013,
       if_to_id_instr[12]);
  nand u_decode_g1997 (u_decode_n_2949, u_decode_n_2855,
       if_to_id_instr[25]);
  or u_decode_g1998 (u_decode_n_2961, u_decode_n_2818, wc38);
  not gc38 (wc38, if_to_id_instr[18]);
  or u_decode_g1999 (u_decode_n_3127, u_decode_n_2811, wc39);
  not gc39 (wc39, if_to_id_instr[21]);
  nand u_decode_g2000 (u_decode_n_2987, u_decode_n_2855,
       if_to_id_instr[27]);
  or u_decode_g2001 (u_decode_n_3128, u_decode_n_2813, wc40);
  not gc40 (wc40, if_to_id_instr[7]);
  or u_decode_g2002 (u_decode_n_2985, u_decode_n_2818, wc41);
  not gc41 (wc41, if_to_id_instr[19]);
  or u_decode_g2003 (u_decode_n_2950, u_decode_n_2818, wc42);
  not gc42 (wc42, if_to_id_instr[17]);
  or u_decode_g2004 (u_decode_n_3149, u_decode_n_2811, wc43);
  not gc43 (wc43, if_to_id_instr[24]);
  nand u_decode_g2005 (u_decode_n_2975, u_decode_n_2855,
       if_to_id_instr[29]);
  or u_decode_g2006 (u_decode_n_2974, u_decode_n_2818, wc44);
  not gc44 (wc44, if_to_id_instr[21]);
  nand u_decode_g2007 (u_decode_n_2848, u_decode_n_2816,
       u_decode_n_2811);
  or u_decode_g2008 (u_decode_n_3151, u_decode_n_2818, wc45);
  not gc45 (wc45, if_to_id_instr[15]);
  or u_decode_g2009 (u_decode_n_3152, u_decode_n_2813, wc46);
  not gc46 (wc46, if_to_id_instr[10]);
  nand u_decode_g2010 (u_decode_n_3106, u_decode_n_3101,
       u_decode_n_3102);
  or u_decode_g2011 (u_decode_n_3013, if_to_id_instr[31],
       u_decode_n_2804);
  or u_decode_g2012 (u_decode_n_2928, u_decode_n_2789, wc47);
  not gc47 (wc47, if_to_id_instr[14]);
  or u_decode_g2013 (u_decode_n_2811, u_decode_n_2810, wc48);
  not gc48 (wc48, if_to_id_instr[3]);
  or u_decode_g2014 (u_decode_n_2813, u_decode_n_2889, wc49);
  not gc49 (wc49, if_to_id_instr[5]);
  nand u_decode_g2015 (u_decode_n_2855, u_decode_n_2889,
       u_decode_n_2822);
  or u_decode_g2016 (u_decode_n_2818, wc50, u_decode_n_2804);
  not gc50 (wc50, if_to_id_instr[2]);
  nand u_decode_g2017 (u_decode_n_775, u_decode_n_2889,
       u_decode_n_2925);
  or u_decode_g2018 (u_decode_n_3037, u_decode_n_2816, wc51);
  not gc51 (wc51, if_to_id_instr[7]);
  or u_decode_g2019 (u_decode_n_3056, u_decode_n_2822, wc52);
  not gc52 (wc52, if_to_id_instr[24]);
  or u_decode_g2020 (u_decode_n_3078, u_decode_n_2822, wc53);
  not gc53 (wc53, if_to_id_instr[21]);
  or u_decode_g2021 (u_decode_n_3080, u_decode_n_2816, wc54);
  not gc54 (wc54, if_to_id_instr[9]);
  or u_decode_g2022 (u_decode_n_3101, u_decode_n_2816, wc55);
  not gc55 (wc55, if_to_id_instr[10]);
  or u_decode_g2023 (u_decode_n_3102, u_decode_n_2822, wc56);
  not gc56 (wc56, if_to_id_instr[22]);
  or u_decode_g2024 (u_decode_n_3126, u_decode_n_2822, wc57);
  not gc57 (wc57, if_to_id_instr[20]);
  or u_decode_g2025 (u_decode_n_2925, u_decode_n_2788,
       if_to_id_instr[5]);
  or u_decode_g2026 (u_decode_n_3129, u_decode_n_2816, wc58);
  not gc58 (wc58, if_to_id_instr[8]);
  or u_decode_g2027 (u_decode_n_3150, u_decode_n_2822, wc59);
  not gc59 (wc59, if_to_id_instr[23]);
  or u_decode_g2028 (u_decode_n_3153, u_decode_n_2816, wc60);
  not gc60 (wc60, if_to_id_instr[11]);
  or u_decode_g2029 (u_decode_n_2810, u_decode_n_3162, i_rstn);
  not u_decode_g2030 (u_decode_n_772, u_decode_n_2810);
  or u_decode_g2031 (u_decode_n_2804, u_decode_n_2919, wc61);
  not gc61 (wc61, if_to_id_instr[5]);
  or u_decode_g2032 (u_decode_n_2789, wc62, u_decode_n_2788);
  not gc62 (wc62, if_to_id_instr[4]);
  not u_decode_g2033 (u_decode_n_706, u_decode_n_2789);
  or u_decode_g2034 (u_decode_n_2889, u_decode_n_2788,
       if_to_id_instr[4]);
  or u_decode_g2035 (u_decode_n_2816, u_decode_n_2922,
       if_to_id_instr[2]);
  not u_decode_g2036 (u_decode_n_709, u_decode_n_2816);
  or u_decode_g2037 (u_decode_n_2919, u_decode_n_2918, wc63);
  not gc63 (wc63, if_to_id_instr[4]);
  or u_decode_g2038 (u_decode_n_2788, u_decode_n_2918,
       if_to_id_instr[2]);
  or u_decode_g2039 (u_decode_n_2822, wc64, u_decode_n_2786);
  not gc64 (wc64, u_decode_n_2895);
  not u_decode_g2040 (u_decode_n_778, u_decode_n_2822);
  or u_decode_g2041 (u_decode_n_3162, u_decode_n_3161, wc65);
  not gc65 (wc65, if_to_id_instr[0]);
  nand u_decode_g2042 (u_decode_n_2895, u_decode_n_2912,
       u_decode_n_2913);
  or u_decode_g2043 (u_decode_n_2922, u_decode_n_2808, u_decode_n_2786);
  or u_decode_g2044 (u_decode_n_2918, u_decode_n_2786,
       if_to_id_instr[6]);
  or u_decode_g2045 (u_decode_n_3161, u_decode_n_2913, wc66);
  not gc66 (wc66, if_to_id_instr[1]);
  or u_decode_g2046 (u_decode_n_2913, u_decode_n_2808, wc67);
  not gc67 (wc67, if_to_id_instr[2]);
  or u_decode_g2047 (u_decode_n_2786, u_decode_n_2904, i_rstn);
  or u_decode_g2048 (u_decode_n_2808, u_decode_n_2898, wc68);
  not gc68 (wc68, if_to_id_instr[5]);
  or u_decode_g2049 (u_decode_n_2904, u_decode_n_2903, wc69);
  not gc69 (wc69, if_to_id_instr[0]);
  or u_decode_g2050 (u_decode_n_2912, u_decode_n_2911,
       if_to_id_instr[2]);
  or u_decode_g2051 (u_decode_n_2898, wc70, if_to_id_instr[4]);
  not gc70 (wc70, if_to_id_instr[6]);
  or u_decode_g2052 (u_decode_n_2911, if_to_id_instr[6],
       if_to_id_instr[5]);
  or u_decode_g2053 (u_decode_n_2903, if_to_id_instr[3], wc71);
  not gc71 (wc71, if_to_id_instr[1]);
  CDN_flop \u_decode_o_alu_op_buffer_2_reg[0] (.clk (i_clk), .d
       (u_decode_n_700), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_alu_op[0]));
  CDN_flop \u_decode_o_alu_op_buffer_2_reg[1] (.clk (i_clk), .d
       (u_decode_n_703), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_alu_op[1]));
  CDN_flop u_decode_o_arith_buffer_2_reg(.clk (i_clk), .d
       (u_decode_n_706), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_arith));
  CDN_flop u_decode_o_branch_buffer_2_reg(.clk (i_clk), .d
       (u_decode_n_709), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_branch));
  CDN_flop \u_decode_o_imm_buffer_2_reg[0] (.clk (i_clk), .d
       (u_decode_n_712), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[0]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[1] (.clk (i_clk), .d
       (u_decode_n_715), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[1]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[2] (.clk (i_clk), .d
       (u_decode_n_718), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[2]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[3] (.clk (i_clk), .d
       (u_decode_n_721), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[3]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[4] (.clk (i_clk), .d
       (u_decode_n_724), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[4]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[5] (.clk (i_clk), .d
       (u_decode_n_727), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[5]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[6] (.clk (i_clk), .d
       (u_decode_n_730), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[6]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[7] (.clk (i_clk), .d
       (u_decode_n_733), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[7]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[8] (.clk (i_clk), .d
       (u_decode_n_736), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[8]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[9] (.clk (i_clk), .d
       (u_decode_n_739), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[9]));
  CDN_flop \u_decode_o_imm_buffer_2_reg[10] (.clk (i_clk), .d
       (u_decode_n_742), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_imm[10]));
  CDN_flop u_decode_o_jump_buffer_2_reg(.clk (i_clk), .d
       (u_decode_n_772), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_jump));
  CDN_flop u_decode_o_rw_buffer_2_reg(.clk (i_clk), .d
       (u_decode_n_775), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_rw));
  CDN_flop u_decode_o_src_imm_buffer_2_reg(.clk (i_clk), .d
       (u_decode_n_778), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (id_to_ex_src_imm));
  CDN_flop u_execute_branch_taken_reg(.clk (i_clk), .d (1'b0), .sena
       (1'b0), .aclr (u_execute_n_2541), .apre (1'b0), .srl (1'b1),
       .srd (id_to_ex_branch), .q (u_execute_branch_taken));
  CDN_flop \u_execute_buffer_alu_result_reg[2] (.clk (i_clk), .d
       (u_execute_n_976), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[2]));
  CDN_flop \u_execute_buffer_alu_result_reg[3] (.clk (i_clk), .d
       (u_execute_n_978), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[3]));
  CDN_flop \u_execute_buffer_alu_result_reg[4] (.clk (i_clk), .d
       (u_execute_n_980), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[4]));
  CDN_flop \u_execute_buffer_alu_result_reg[5] (.clk (i_clk), .d
       (u_execute_n_982), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[5]));
  CDN_flop \u_execute_buffer_alu_result_reg[6] (.clk (i_clk), .d
       (u_execute_n_984), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[6]));
  CDN_flop \u_execute_buffer_alu_result_reg[7] (.clk (i_clk), .d
       (u_execute_n_986), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[7]));
  CDN_flop \u_execute_buffer_alu_result_reg[8] (.clk (i_clk), .d
       (u_execute_n_988), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[8]));
  CDN_flop \u_execute_buffer_alu_result_reg[9] (.clk (i_clk), .d
       (u_execute_n_990), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[9]));
  CDN_flop \u_execute_buffer_alu_result_reg[10] (.clk (i_clk), .d
       (u_execute_n_992), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_me_result[10]));
  CDN_flop \u_execute_buffer_pc_target_reg[2] (.clk (i_clk), .d
       (id_to_ex_imm[2]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[2]));
  CDN_flop \u_execute_buffer_pc_target_reg[3] (.clk (i_clk), .d
       (id_to_ex_imm[3]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[3]));
  CDN_flop \u_execute_buffer_pc_target_reg[4] (.clk (i_clk), .d
       (id_to_ex_imm[4]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[4]));
  CDN_flop \u_execute_buffer_pc_target_reg[5] (.clk (i_clk), .d
       (id_to_ex_imm[5]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[5]));
  CDN_flop \u_execute_buffer_pc_target_reg[6] (.clk (i_clk), .d
       (id_to_ex_imm[6]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[6]));
  CDN_flop \u_execute_buffer_pc_target_reg[7] (.clk (i_clk), .d
       (id_to_ex_imm[7]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[7]));
  CDN_flop \u_execute_buffer_pc_target_reg[8] (.clk (i_clk), .d
       (id_to_ex_imm[8]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[8]));
  CDN_flop \u_execute_buffer_pc_target_reg[9] (.clk (i_clk), .d
       (id_to_ex_imm[9]), .sena (1'b1), .aclr (u_execute_n_2541), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (ex_to_if_pc_target[9]));
  CDN_flop \u_execute_buffer_pc_target_reg[10] (.clk (i_clk), .d
       (id_to_ex_imm[10]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (ex_to_if_pc_target[10]));
  CDN_flop u_execute_buffer_pc_transfer_reg(.clk (i_clk), .d
       (u_execute_n_2543), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (ex_to_if_pc_transfer));
  CDN_flop u_execute_buffer_we_reg(.clk (i_clk), .d (id_to_ex_rw),
       .sena (1'b1), .aclr (u_execute_n_2541), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (ex_to_me_we));
  or u_execute_g2 (u_execute_n_2543, id_to_ex_jump,
       u_execute_branch_taken);
  or u_execute_g3 (u_execute_n_2546, id_to_ex_imm[0], id_to_ex_imm[1]);
  or u_execute_g20 (u_execute_n_2562, id_to_ex_imm[2],
       u_execute_n_2546);
  or u_execute_g28 (u_execute_n_2570, id_to_ex_imm[3],
       u_execute_n_2562);
  or u_execute_g36 (u_execute_n_2578, id_to_ex_imm[4],
       u_execute_n_2570);
  or u_execute_g44 (u_execute_n_2586, id_to_ex_imm[5],
       u_execute_n_2578);
  or u_execute_g52 (u_execute_n_2594, id_to_ex_imm[6],
       u_execute_n_2586);
  or u_execute_g60 (u_execute_n_2602, id_to_ex_imm[7],
       u_execute_n_2594);
  or u_execute_g1752 (u_execute_n_2610, id_to_ex_imm[8],
       u_execute_n_2602);
  or u_execute_g1842 (u_execute_n_2626, u_execute_n_2610,
       id_to_ex_imm[9]);
  or u_execute_g1957 (u_execute_n_992, u_execute_n_2802, wc72);
  not gc72 (wc72, u_execute_n_2803);
  nand u_execute_g1958 (u_execute_n_2803, u_execute_n_2627,
       id_to_ex_imm[10]);
  or u_execute_g1959 (u_execute_n_990, u_execute_n_2787, wc73);
  not gc73 (wc73, u_execute_n_2788);
  nand u_execute_g1960 (u_execute_n_2788, u_execute_n_2628,
       id_to_ex_imm[9]);
  nand u_execute_g1961 (u_execute_n_2627, u_execute_n_2555,
       u_execute_n_2773);
  nand u_execute_g1962 (u_execute_n_2802, u_execute_n_2800,
       u_execute_n_2801);
  or u_execute_g1963 (u_execute_n_988, u_execute_n_2769, wc74);
  not gc74 (wc74, u_execute_n_2770);
  or u_execute_g1964 (u_execute_n_2801, u_execute_n_2799, wc75);
  not gc75 (wc75, u_execute_n_2626);
  or u_execute_g1965 (u_execute_n_2773, u_execute_n_2552,
       u_execute_n_2626);
  or u_execute_g1966 (u_execute_n_986, u_execute_n_2751, wc76);
  not gc76 (wc76, u_execute_n_2752);
  nand u_execute_g1967 (u_execute_n_2787, u_execute_n_2785,
       u_execute_n_2786);
  nand u_execute_g1968 (u_execute_n_2628, u_execute_n_2555,
       u_execute_n_2755);
  nand u_execute_g1969 (u_execute_n_2770, u_execute_n_2629,
       id_to_ex_imm[8]);
  nand u_execute_g1970 (u_execute_n_2769, u_execute_n_2767,
       u_execute_n_2768);
  nand u_execute_g1971 (u_execute_n_2752, u_execute_n_2630,
       id_to_ex_imm[7]);
  or u_execute_g1972 (u_execute_n_2786, u_execute_n_2784, wc77);
  not gc77 (wc77, u_execute_n_2610);
  nand u_execute_g1973 (u_execute_n_2629, u_execute_n_2555,
       u_execute_n_2737);
  or u_execute_g1974 (u_execute_n_984, u_execute_n_2733, wc78);
  not gc78 (wc78, u_execute_n_2734);
  or u_execute_g1975 (u_execute_n_2755, u_execute_n_2610,
       u_execute_n_2552);
  or u_execute_g1976 (u_execute_n_2768, u_execute_n_2766, wc79);
  not gc79 (wc79, u_execute_n_2602);
  nand u_execute_g1977 (u_execute_n_2630, u_execute_n_2555,
       u_execute_n_2719);
  nand u_execute_g1978 (u_execute_n_2733, u_execute_n_2731,
       u_execute_n_2732);
  nand u_execute_g1979 (u_execute_n_2734, u_execute_n_2631,
       id_to_ex_imm[6]);
  nand u_execute_g1980 (u_execute_n_2751, u_execute_n_2749,
       u_execute_n_2750);
  or u_execute_g1981 (u_execute_n_2737, u_execute_n_2602,
       u_execute_n_2552);
  or u_execute_g1982 (u_execute_n_982, u_execute_n_2715, wc80);
  not gc80 (wc80, u_execute_n_2716);
  or u_execute_g1983 (u_execute_n_978, wc81, u_execute_n_2662);
  not gc81 (wc81, u_execute_n_2661);
  nand u_execute_g1984 (u_execute_n_2715, u_execute_n_2713,
       u_execute_n_2714);
  nand u_execute_g1985 (u_execute_n_2716, u_execute_n_2632,
       id_to_ex_imm[5]);
  or u_execute_g1986 (u_execute_n_2750, u_execute_n_2748, wc82);
  not gc82 (wc82, u_execute_n_2594);
  or u_execute_g1987 (u_execute_n_2719, u_execute_n_2594,
       u_execute_n_2552);
  nand u_execute_g1988 (u_execute_n_2631, u_execute_n_2555,
       u_execute_n_2701);
  or u_execute_g1989 (u_execute_n_980, wc83, u_execute_n_2698);
  not gc83 (wc83, u_execute_n_2697);
  or u_execute_g1990 (u_execute_n_976, wc84, u_execute_n_2677);
  not gc84 (wc84, u_execute_n_2676);
  or u_execute_g1991 (u_execute_n_2732, u_execute_n_2730,
       u_execute_n_2558);
  or u_execute_g1992 (u_execute_n_2730, id_to_ex_imm[6], wc85);
  not gc85 (wc85, u_execute_n_2586);
  nand u_execute_g1993 (u_execute_n_2677, u_execute_n_2674,
       u_execute_n_2675);
  nand u_execute_g1994 (u_execute_n_2676, u_execute_n_2634,
       id_to_ex_imm[2]);
  nand u_execute_g1995 (u_execute_n_2662, u_execute_n_2659,
       u_execute_n_2660);
  nand u_execute_g1996 (u_execute_n_2632, u_execute_n_2555,
       u_execute_n_2683);
  or u_execute_g1997 (u_execute_n_2713, u_execute_n_2712,
       u_execute_n_2558);
  nand u_execute_g1998 (u_execute_n_2697, u_execute_n_2635,
       id_to_ex_imm[4]);
  nand u_execute_g1999 (u_execute_n_2661, u_execute_n_2633,
       id_to_ex_imm[3]);
  or u_execute_g2000 (u_execute_n_2701, u_execute_n_2586,
       u_execute_n_2552);
  nand u_execute_g2001 (u_execute_n_2698, u_execute_n_2695,
       u_execute_n_2696);
  nand u_execute_g2002 (u_execute_n_2633, u_execute_n_2555,
       u_execute_n_2644);
  or u_execute_g2003 (u_execute_n_2695, u_execute_n_2694,
       u_execute_n_2558);
  or u_execute_g2004 (u_execute_n_2766, id_to_ex_imm[8],
       u_execute_n_2558);
  or u_execute_g2005 (u_execute_n_2799, id_to_ex_imm[10],
       u_execute_n_2558);
  or u_execute_g2006 (u_execute_n_2683, u_execute_n_2578,
       u_execute_n_2552);
  nand u_execute_g2007 (u_execute_n_2635, u_execute_n_2555,
       u_execute_n_2680);
  or u_execute_g2008 (u_execute_n_2784, id_to_ex_imm[9],
       u_execute_n_2558);
  or u_execute_g2009 (u_execute_n_2659, u_execute_n_2658,
       u_execute_n_2558);
  or u_execute_g2010 (u_execute_n_2712, id_to_ex_imm[5], wc86);
  not gc86 (wc86, u_execute_n_2578);
  or u_execute_g2011 (u_execute_n_2748, id_to_ex_imm[7],
       u_execute_n_2558);
  nand u_execute_g2012 (u_execute_n_2634, u_execute_n_2555,
       u_execute_n_2647);
  or u_execute_g2013 (u_execute_n_2674, u_execute_n_2673,
       u_execute_n_2558);
  or u_execute_g2014 (u_execute_n_2694, id_to_ex_imm[4], wc87);
  not gc87 (wc87, u_execute_n_2570);
  or u_execute_g2015 (u_execute_n_2644, u_execute_n_2562,
       u_execute_n_2552);
  or u_execute_g2016 (u_execute_n_2680, u_execute_n_2570,
       u_execute_n_2552);
  or u_execute_g2017 (u_execute_n_2555, u_execute_n_2552,
       id_to_ex_arith);
  or u_execute_g2018 (u_execute_n_2558, wc88, u_execute_n_2552);
  not gc88 (wc88, id_to_ex_arith);
  or u_execute_g2019 (u_execute_n_2647, u_execute_n_2546,
       u_execute_n_2552);
  or u_execute_g2020 (u_execute_n_2552, u_execute_n_2641, wc89);
  not gc89 (wc89, id_to_ex_rw);
  or u_execute_g2021 (u_execute_n_2658, id_to_ex_imm[3], wc90);
  not gc90 (wc90, u_execute_n_2562);
  or u_execute_g2022 (u_execute_n_2641, wc91, u_execute_n_2640);
  not gc91 (wc91, id_to_ex_src_imm);
  or u_execute_g2023 (u_execute_n_2673, id_to_ex_imm[2], wc92);
  not gc92 (wc92, u_execute_n_2546);
  or u_execute_g2024 (u_execute_n_2731, id_to_ex_rw, wc93);
  not gc93 (wc93, ex_to_me_result[6]);
  or u_execute_g2025 (u_execute_n_2675, id_to_ex_rw, wc94);
  not gc94 (wc94, ex_to_me_result[2]);
  or u_execute_g2026 (u_execute_n_2714, id_to_ex_rw, wc95);
  not gc95 (wc95, ex_to_me_result[5]);
  or u_execute_g2027 (u_execute_n_2749, id_to_ex_rw, wc96);
  not gc96 (wc96, ex_to_me_result[7]);
  or u_execute_g2028 (u_execute_n_2767, id_to_ex_rw, wc97);
  not gc97 (wc97, ex_to_me_result[8]);
  or u_execute_g2029 (u_execute_n_2660, id_to_ex_rw, wc98);
  not gc98 (wc98, ex_to_me_result[3]);
  or u_execute_g2030 (u_execute_n_2785, id_to_ex_rw, wc99);
  not gc99 (wc99, ex_to_me_result[9]);
  or u_execute_g2031 (u_execute_n_2800, id_to_ex_rw, wc100);
  not gc100 (wc100, ex_to_me_result[10]);
  or u_execute_g2032 (u_execute_n_2640, id_to_ex_alu_op[1],
       id_to_ex_alu_op[0]);
  or u_execute_g2033 (u_execute_n_2696, id_to_ex_rw, wc101);
  not gc101 (wc101, ex_to_me_result[4]);
  CDN_flop \u_fetch_InstructionBuffer_reg[0] (.clk (i_clk), .d
       (i_imem_read[0]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[0]));
  CDN_flop \u_fetch_InstructionBuffer_reg[1] (.clk (i_clk), .d
       (i_imem_read[1]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[1]));
  CDN_flop \u_fetch_InstructionBuffer_reg[2] (.clk (i_clk), .d
       (i_imem_read[2]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[2]));
  CDN_flop \u_fetch_InstructionBuffer_reg[3] (.clk (i_clk), .d
       (i_imem_read[3]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[3]));
  CDN_flop \u_fetch_InstructionBuffer_reg[4] (.clk (i_clk), .d
       (i_imem_read[4]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[4]));
  CDN_flop \u_fetch_InstructionBuffer_reg[5] (.clk (i_clk), .d
       (i_imem_read[5]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[5]));
  CDN_flop \u_fetch_InstructionBuffer_reg[6] (.clk (i_clk), .d
       (i_imem_read[6]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[6]));
  CDN_flop \u_fetch_InstructionBuffer_reg[7] (.clk (i_clk), .d
       (i_imem_read[7]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[7]));
  CDN_flop \u_fetch_InstructionBuffer_reg[8] (.clk (i_clk), .d
       (i_imem_read[8]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[8]));
  CDN_flop \u_fetch_InstructionBuffer_reg[9] (.clk (i_clk), .d
       (i_imem_read[9]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[9]));
  CDN_flop \u_fetch_InstructionBuffer_reg[10] (.clk (i_clk), .d
       (i_imem_read[10]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[10]));
  CDN_flop \u_fetch_InstructionBuffer_reg[11] (.clk (i_clk), .d
       (i_imem_read[11]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[11]));
  CDN_flop \u_fetch_InstructionBuffer_reg[12] (.clk (i_clk), .d
       (i_imem_read[12]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[12]));
  CDN_flop \u_fetch_InstructionBuffer_reg[13] (.clk (i_clk), .d
       (i_imem_read[13]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[13]));
  CDN_flop \u_fetch_InstructionBuffer_reg[14] (.clk (i_clk), .d
       (i_imem_read[14]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[14]));
  CDN_flop \u_fetch_InstructionBuffer_reg[15] (.clk (i_clk), .d
       (i_imem_read[15]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[15]));
  CDN_flop \u_fetch_InstructionBuffer_reg[16] (.clk (i_clk), .d
       (i_imem_read[16]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[16]));
  CDN_flop \u_fetch_InstructionBuffer_reg[17] (.clk (i_clk), .d
       (i_imem_read[17]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[17]));
  CDN_flop \u_fetch_InstructionBuffer_reg[18] (.clk (i_clk), .d
       (i_imem_read[18]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[18]));
  CDN_flop \u_fetch_InstructionBuffer_reg[19] (.clk (i_clk), .d
       (i_imem_read[19]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[19]));
  CDN_flop \u_fetch_InstructionBuffer_reg[20] (.clk (i_clk), .d
       (i_imem_read[20]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[20]));
  CDN_flop \u_fetch_InstructionBuffer_reg[21] (.clk (i_clk), .d
       (i_imem_read[21]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[21]));
  CDN_flop \u_fetch_InstructionBuffer_reg[22] (.clk (i_clk), .d
       (i_imem_read[22]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[22]));
  CDN_flop \u_fetch_InstructionBuffer_reg[23] (.clk (i_clk), .d
       (i_imem_read[23]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[23]));
  CDN_flop \u_fetch_InstructionBuffer_reg[24] (.clk (i_clk), .d
       (i_imem_read[24]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[24]));
  CDN_flop \u_fetch_InstructionBuffer_reg[25] (.clk (i_clk), .d
       (i_imem_read[25]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[25]));
  CDN_flop \u_fetch_InstructionBuffer_reg[26] (.clk (i_clk), .d
       (i_imem_read[26]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[26]));
  CDN_flop \u_fetch_InstructionBuffer_reg[27] (.clk (i_clk), .d
       (i_imem_read[27]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[27]));
  CDN_flop \u_fetch_InstructionBuffer_reg[28] (.clk (i_clk), .d
       (i_imem_read[28]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[28]));
  CDN_flop \u_fetch_InstructionBuffer_reg[29] (.clk (i_clk), .d
       (i_imem_read[29]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[29]));
  CDN_flop \u_fetch_InstructionBuffer_reg[30] (.clk (i_clk), .d
       (i_imem_read[30]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[30]));
  CDN_flop \u_fetch_InstructionBuffer_reg[31] (.clk (i_clk), .d
       (i_imem_read[31]), .sena (1'b1), .aclr (i_rstn), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (if_to_id_instr[31]));
  CDN_flop \u_fetch_u_add_pc_reg[2] (.clk (i_clk), .d
       (u_fetch_u_add_n_79), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[0]));
  CDN_flop \u_fetch_u_add_pc_reg[3] (.clk (i_clk), .d
       (u_fetch_u_add_n_81), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[1]));
  CDN_flop \u_fetch_u_add_pc_reg[4] (.clk (i_clk), .d
       (u_fetch_u_add_n_83), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[2]));
  CDN_flop \u_fetch_u_add_pc_reg[5] (.clk (i_clk), .d
       (u_fetch_u_add_n_85), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[3]));
  CDN_flop \u_fetch_u_add_pc_reg[6] (.clk (i_clk), .d
       (u_fetch_u_add_n_87), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[4]));
  CDN_flop \u_fetch_u_add_pc_reg[7] (.clk (i_clk), .d
       (u_fetch_u_add_n_89), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[5]));
  CDN_flop \u_fetch_u_add_pc_reg[8] (.clk (i_clk), .d
       (u_fetch_u_add_n_91), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[6]));
  CDN_flop \u_fetch_u_add_pc_reg[9] (.clk (i_clk), .d
       (u_fetch_u_add_n_93), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[7]));
  CDN_flop \u_fetch_u_add_pc_reg[10] (.clk (i_clk), .d
       (u_fetch_u_add_n_95), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_imem_addr[8]));
  not u_memory_g637 (u_execute_n_2541, i_rstn);
  CDN_flop \u_memory_o_dmem_addr_reg[0] (.clk (i_clk), .d
       (ex_to_me_result[2]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[0]));
  CDN_flop \u_memory_o_dmem_addr_reg[1] (.clk (i_clk), .d
       (ex_to_me_result[3]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[1]));
  CDN_flop \u_memory_o_dmem_addr_reg[2] (.clk (i_clk), .d
       (ex_to_me_result[4]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[2]));
  CDN_flop \u_memory_o_dmem_addr_reg[3] (.clk (i_clk), .d
       (ex_to_me_result[5]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[3]));
  CDN_flop \u_memory_o_dmem_addr_reg[4] (.clk (i_clk), .d
       (ex_to_me_result[6]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[4]));
  CDN_flop \u_memory_o_dmem_addr_reg[5] (.clk (i_clk), .d
       (ex_to_me_result[7]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[5]));
  CDN_flop \u_memory_o_dmem_addr_reg[6] (.clk (i_clk), .d
       (ex_to_me_result[8]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[6]));
  CDN_flop \u_memory_o_dmem_addr_reg[7] (.clk (i_clk), .d
       (ex_to_me_result[9]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[7]));
  CDN_flop \u_memory_o_dmem_addr_reg[8] (.clk (i_clk), .d
       (ex_to_me_result[10]), .sena (1'b1), .aclr (u_execute_n_2541),
       .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_dmem_addr[8]));
  CDN_flop u_memory_o_dmem_en_reg(.clk (i_clk), .d (1'b1), .sena
       (1'b1), .aclr (u_execute_n_2541), .apre (1'b0), .srl (1'b1),
       .srd (1'b1), .q (o_dmem_en));
  CDN_flop u_memory_o_dmem_we_reg(.clk (i_clk), .d (ex_to_me_we), .sena
       (1'b1), .aclr (u_execute_n_2541), .apre (1'b0), .srl (1'b0),
       .srd (1'b0), .q (o_dmem_we));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
