
//input ports
add mapped point i_rstn i_rstn -type PI PI
add mapped point i_clk i_clk -type PI PI
add mapped point i_imem_read[31] i_imem_read[31] -type PI PI
add mapped point i_imem_read[30] i_imem_read[30] -type PI PI
add mapped point i_imem_read[29] i_imem_read[29] -type PI PI
add mapped point i_imem_read[28] i_imem_read[28] -type PI PI
add mapped point i_imem_read[27] i_imem_read[27] -type PI PI
add mapped point i_imem_read[26] i_imem_read[26] -type PI PI
add mapped point i_imem_read[25] i_imem_read[25] -type PI PI
add mapped point i_imem_read[24] i_imem_read[24] -type PI PI
add mapped point i_imem_read[23] i_imem_read[23] -type PI PI
add mapped point i_imem_read[22] i_imem_read[22] -type PI PI
add mapped point i_imem_read[21] i_imem_read[21] -type PI PI
add mapped point i_imem_read[20] i_imem_read[20] -type PI PI
add mapped point i_imem_read[19] i_imem_read[19] -type PI PI
add mapped point i_imem_read[18] i_imem_read[18] -type PI PI
add mapped point i_imem_read[17] i_imem_read[17] -type PI PI
add mapped point i_imem_read[16] i_imem_read[16] -type PI PI
add mapped point i_imem_read[15] i_imem_read[15] -type PI PI
add mapped point i_imem_read[14] i_imem_read[14] -type PI PI
add mapped point i_imem_read[13] i_imem_read[13] -type PI PI
add mapped point i_imem_read[12] i_imem_read[12] -type PI PI
add mapped point i_imem_read[11] i_imem_read[11] -type PI PI
add mapped point i_imem_read[10] i_imem_read[10] -type PI PI
add mapped point i_imem_read[9] i_imem_read[9] -type PI PI
add mapped point i_imem_read[8] i_imem_read[8] -type PI PI
add mapped point i_imem_read[7] i_imem_read[7] -type PI PI
add mapped point i_imem_read[6] i_imem_read[6] -type PI PI
add mapped point i_imem_read[5] i_imem_read[5] -type PI PI
add mapped point i_imem_read[4] i_imem_read[4] -type PI PI
add mapped point i_imem_read[3] i_imem_read[3] -type PI PI
add mapped point i_imem_read[2] i_imem_read[2] -type PI PI
add mapped point i_imem_read[1] i_imem_read[1] -type PI PI
add mapped point i_imem_read[0] i_imem_read[0] -type PI PI
add mapped point i_dmem_read[31] i_dmem_read[31] -type PI PI
add mapped point i_dmem_read[30] i_dmem_read[30] -type PI PI
add mapped point i_dmem_read[29] i_dmem_read[29] -type PI PI
add mapped point i_dmem_read[28] i_dmem_read[28] -type PI PI
add mapped point i_dmem_read[27] i_dmem_read[27] -type PI PI
add mapped point i_dmem_read[26] i_dmem_read[26] -type PI PI
add mapped point i_dmem_read[25] i_dmem_read[25] -type PI PI
add mapped point i_dmem_read[24] i_dmem_read[24] -type PI PI
add mapped point i_dmem_read[23] i_dmem_read[23] -type PI PI
add mapped point i_dmem_read[22] i_dmem_read[22] -type PI PI
add mapped point i_dmem_read[21] i_dmem_read[21] -type PI PI
add mapped point i_dmem_read[20] i_dmem_read[20] -type PI PI
add mapped point i_dmem_read[19] i_dmem_read[19] -type PI PI
add mapped point i_dmem_read[18] i_dmem_read[18] -type PI PI
add mapped point i_dmem_read[17] i_dmem_read[17] -type PI PI
add mapped point i_dmem_read[16] i_dmem_read[16] -type PI PI
add mapped point i_dmem_read[15] i_dmem_read[15] -type PI PI
add mapped point i_dmem_read[14] i_dmem_read[14] -type PI PI
add mapped point i_dmem_read[13] i_dmem_read[13] -type PI PI
add mapped point i_dmem_read[12] i_dmem_read[12] -type PI PI
add mapped point i_dmem_read[11] i_dmem_read[11] -type PI PI
add mapped point i_dmem_read[10] i_dmem_read[10] -type PI PI
add mapped point i_dmem_read[9] i_dmem_read[9] -type PI PI
add mapped point i_dmem_read[8] i_dmem_read[8] -type PI PI
add mapped point i_dmem_read[7] i_dmem_read[7] -type PI PI
add mapped point i_dmem_read[6] i_dmem_read[6] -type PI PI
add mapped point i_dmem_read[5] i_dmem_read[5] -type PI PI
add mapped point i_dmem_read[4] i_dmem_read[4] -type PI PI
add mapped point i_dmem_read[3] i_dmem_read[3] -type PI PI
add mapped point i_dmem_read[2] i_dmem_read[2] -type PI PI
add mapped point i_dmem_read[1] i_dmem_read[1] -type PI PI
add mapped point i_dmem_read[0] i_dmem_read[0] -type PI PI
add mapped point i_scan_en i_scan_en -type PI PI
add mapped point i_test_mode i_test_mode -type PI PI
add mapped point i_tdi i_tdi -type PI PI

//output ports
add mapped point o_imem_en o_imem_en -type PO PO
add mapped point o_imem_addr[8] o_imem_addr[8] -type PO PO
add mapped point o_imem_addr[7] o_imem_addr[7] -type PO PO
add mapped point o_imem_addr[6] o_imem_addr[6] -type PO PO
add mapped point o_imem_addr[5] o_imem_addr[5] -type PO PO
add mapped point o_imem_addr[4] o_imem_addr[4] -type PO PO
add mapped point o_imem_addr[3] o_imem_addr[3] -type PO PO
add mapped point o_imem_addr[2] o_imem_addr[2] -type PO PO
add mapped point o_imem_addr[1] o_imem_addr[1] -type PO PO
add mapped point o_imem_addr[0] o_imem_addr[0] -type PO PO
add mapped point o_dmem_en o_dmem_en -type PO PO
add mapped point o_dmem_we o_dmem_we -type PO PO
add mapped point o_dmem_addr[8] o_dmem_addr[8] -type PO PO
add mapped point o_dmem_addr[7] o_dmem_addr[7] -type PO PO
add mapped point o_dmem_addr[6] o_dmem_addr[6] -type PO PO
add mapped point o_dmem_addr[5] o_dmem_addr[5] -type PO PO
add mapped point o_dmem_addr[4] o_dmem_addr[4] -type PO PO
add mapped point o_dmem_addr[3] o_dmem_addr[3] -type PO PO
add mapped point o_dmem_addr[2] o_dmem_addr[2] -type PO PO
add mapped point o_dmem_addr[1] o_dmem_addr[1] -type PO PO
add mapped point o_dmem_addr[0] o_dmem_addr[0] -type PO PO
add mapped point o_dmem_write[31] o_dmem_write[31] -type PO PO
add mapped point o_dmem_write[30] o_dmem_write[30] -type PO PO
add mapped point o_dmem_write[29] o_dmem_write[29] -type PO PO
add mapped point o_dmem_write[28] o_dmem_write[28] -type PO PO
add mapped point o_dmem_write[27] o_dmem_write[27] -type PO PO
add mapped point o_dmem_write[26] o_dmem_write[26] -type PO PO
add mapped point o_dmem_write[25] o_dmem_write[25] -type PO PO
add mapped point o_dmem_write[24] o_dmem_write[24] -type PO PO
add mapped point o_dmem_write[23] o_dmem_write[23] -type PO PO
add mapped point o_dmem_write[22] o_dmem_write[22] -type PO PO
add mapped point o_dmem_write[21] o_dmem_write[21] -type PO PO
add mapped point o_dmem_write[20] o_dmem_write[20] -type PO PO
add mapped point o_dmem_write[19] o_dmem_write[19] -type PO PO
add mapped point o_dmem_write[18] o_dmem_write[18] -type PO PO
add mapped point o_dmem_write[17] o_dmem_write[17] -type PO PO
add mapped point o_dmem_write[16] o_dmem_write[16] -type PO PO
add mapped point o_dmem_write[15] o_dmem_write[15] -type PO PO
add mapped point o_dmem_write[14] o_dmem_write[14] -type PO PO
add mapped point o_dmem_write[13] o_dmem_write[13] -type PO PO
add mapped point o_dmem_write[12] o_dmem_write[12] -type PO PO
add mapped point o_dmem_write[11] o_dmem_write[11] -type PO PO
add mapped point o_dmem_write[10] o_dmem_write[10] -type PO PO
add mapped point o_dmem_write[9] o_dmem_write[9] -type PO PO
add mapped point o_dmem_write[8] o_dmem_write[8] -type PO PO
add mapped point o_dmem_write[7] o_dmem_write[7] -type PO PO
add mapped point o_dmem_write[6] o_dmem_write[6] -type PO PO
add mapped point o_dmem_write[5] o_dmem_write[5] -type PO PO
add mapped point o_dmem_write[4] o_dmem_write[4] -type PO PO
add mapped point o_dmem_write[3] o_dmem_write[3] -type PO PO
add mapped point o_dmem_write[2] o_dmem_write[2] -type PO PO
add mapped point o_dmem_write[1] o_dmem_write[1] -type PO PO
add mapped point o_dmem_write[0] o_dmem_write[0] -type PO PO
add mapped point o_tdo o_tdo -type PO PO

//inout ports




//Sequential Pins
add mapped point u_execute/buffer_alu_result[10]/q u_execute_buffer_alu_result_reg[10]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[9]/q u_execute_buffer_alu_result_reg[9]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[8]/q u_execute_buffer_alu_result_reg[8]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[7]/q u_execute_buffer_alu_result_reg[7]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[6]/q u_execute_buffer_alu_result_reg[6]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[5]/q u_execute_buffer_alu_result_reg[5]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[4]/q u_execute_buffer_alu_result_reg[4]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[3]/q u_execute_buffer_alu_result_reg[3]/Q  -type DFF DFF
add mapped point u_execute/buffer_alu_result[2]/q u_execute_buffer_alu_result_reg[2]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[10]/q u_fetch_u_add_pc_reg[10]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[3]/q u_fetch_u_add_pc_reg[3]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[6]/q u_fetch_u_add_pc_reg[6]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[2]/q u_fetch_u_add_pc_reg[2]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[9]/q u_fetch_u_add_pc_reg[9]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[4]/q u_fetch_u_add_pc_reg[4]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[7]/q u_fetch_u_add_pc_reg[7]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[5]/q u_fetch_u_add_pc_reg[5]/Q  -type DFF DFF
add mapped point u_fetch/u_add/pc[8]/q u_fetch_u_add_pc_reg[8]/Q  -type DFF DFF
add mapped point u_decode/o_alu_op_buffer_2[0]/q u_decode_o_alu_op_buffer_2_reg[0]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[3]/q u_execute_buffer_pc_target_reg[3]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[2]/q u_execute_buffer_pc_target_reg[2]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[2]/q u_execute_buffer_pc_target_reg[2]/QN  -type DFF DFF
add mapped point u_execute/buffer_pc_target[6]/q u_execute_buffer_pc_target_reg[6]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[10]/q u_execute_buffer_pc_target_reg[10]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[1]/q u_decode_o_imm_buffer_2_reg[1]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[0]/q u_decode_o_imm_buffer_2_reg[0]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[3]/q u_decode_o_imm_buffer_2_reg[3]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[8]/q u_execute_buffer_pc_target_reg[8]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[4]/q u_execute_buffer_pc_target_reg[4]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[5]/q u_execute_buffer_pc_target_reg[5]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[7]/q u_execute_buffer_pc_target_reg[7]/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_target[9]/q u_execute_buffer_pc_target_reg[9]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[10]/q u_decode_o_imm_buffer_2_reg[10]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[2]/q u_decode_o_imm_buffer_2_reg[2]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[6]/q u_decode_o_imm_buffer_2_reg[6]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[8]/q u_decode_o_imm_buffer_2_reg[8]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[7]/q u_decode_o_imm_buffer_2_reg[7]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[9]/q u_decode_o_imm_buffer_2_reg[9]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[5]/q u_decode_o_imm_buffer_2_reg[5]/Q  -type DFF DFF
add mapped point u_decode/o_imm_buffer_2[4]/q u_decode_o_imm_buffer_2_reg[4]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_we/q u_memory_o_dmem_we_reg/Q  -type DFF DFF
add mapped point u_decode/o_alu_op_buffer_2[1]/q u_decode_o_alu_op_buffer_2_reg[1]/Q  -type DFF DFF
add mapped point u_execute/buffer_we/q u_execute_buffer_we_reg/Q  -type DFF DFF
add mapped point u_decode/o_src_imm_buffer_2/q u_decode_o_src_imm_buffer_2_reg/Q  -type DFF DFF
add mapped point u_decode/o_arith_buffer_2/q u_decode_o_arith_buffer_2_reg/Q  -type DFF DFF
add mapped point u_execute/buffer_pc_transfer/q u_execute_buffer_pc_transfer_reg/Q  -type DFF DFF
add mapped point u_execute/branch_taken/q u_execute_branch_taken_reg/Q  -type DFF DFF
add mapped point u_decode/o_rw_buffer_2/q u_decode_o_rw_buffer_2_reg/Q  -type DFF DFF
add mapped point u_decode/o_branch_buffer_2/q u_decode_o_branch_buffer_2_reg/Q  -type DFF DFF
add mapped point u_decode/o_jump_buffer_2/q u_decode_o_jump_buffer_2_reg/Q  -type DFF DFF
add mapped point u_memory/o_dmem_en/q u_memory_o_dmem_en_reg/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[16]/q u_fetch_InstructionBuffer_reg[16]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[16]/q u_fetch_InstructionBuffer_reg[16]/QN  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[18]/q u_fetch_InstructionBuffer_reg[18]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[17]/q u_fetch_InstructionBuffer_reg[17]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[19]/q u_fetch_InstructionBuffer_reg[19]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[1]/q u_fetch_InstructionBuffer_reg[1]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[22]/q u_fetch_InstructionBuffer_reg[22]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[6]/q u_fetch_InstructionBuffer_reg[6]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[9]/q u_fetch_InstructionBuffer_reg[9]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[9]/q u_fetch_InstructionBuffer_reg[9]/QN  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[7]/q u_fetch_InstructionBuffer_reg[7]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[10]/q u_fetch_InstructionBuffer_reg[10]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[28]/q u_fetch_InstructionBuffer_reg[28]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[29]/q u_fetch_InstructionBuffer_reg[29]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[30]/q u_fetch_InstructionBuffer_reg[30]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[30]/q u_fetch_InstructionBuffer_reg[30]/QN  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[14]/q u_fetch_InstructionBuffer_reg[14]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[2]/q u_fetch_InstructionBuffer_reg[2]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[15]/q u_fetch_InstructionBuffer_reg[15]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[0]/q u_fetch_InstructionBuffer_reg[0]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[31]/q u_fetch_InstructionBuffer_reg[31]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[23]/q u_fetch_InstructionBuffer_reg[23]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[23]/q u_fetch_InstructionBuffer_reg[23]/QN  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[8]/q u_fetch_InstructionBuffer_reg[8]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[3]/q u_fetch_InstructionBuffer_reg[3]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[11]/q u_fetch_InstructionBuffer_reg[11]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[24]/q u_fetch_InstructionBuffer_reg[24]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[21]/q u_fetch_InstructionBuffer_reg[21]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[21]/q u_fetch_InstructionBuffer_reg[21]/QN  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[13]/q u_fetch_InstructionBuffer_reg[13]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[13]/q u_fetch_InstructionBuffer_reg[13]/QN  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[27]/q u_fetch_InstructionBuffer_reg[27]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[20]/q u_fetch_InstructionBuffer_reg[20]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[26]/q u_fetch_InstructionBuffer_reg[26]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[25]/q u_fetch_InstructionBuffer_reg[25]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[12]/q u_fetch_InstructionBuffer_reg[12]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[12]/q u_fetch_InstructionBuffer_reg[12]/QN  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[5]/q u_fetch_InstructionBuffer_reg[5]/Q  -type DFF DFF
add mapped point u_fetch/InstructionBuffer[4]/q u_fetch_InstructionBuffer_reg[4]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[4]/q u_memory_o_dmem_addr_reg[4]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[8]/q u_memory_o_dmem_addr_reg[8]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[6]/q u_memory_o_dmem_addr_reg[6]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[3]/q u_memory_o_dmem_addr_reg[3]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[5]/q u_memory_o_dmem_addr_reg[5]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[7]/q u_memory_o_dmem_addr_reg[7]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[2]/q u_memory_o_dmem_addr_reg[2]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[0]/q u_memory_o_dmem_addr_reg[0]/Q  -type DFF DFF
add mapped point u_memory/o_dmem_addr[1]/q u_memory_o_dmem_addr_reg[1]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
