
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 26 2024 23:47:34 EST (Nov 27 2024 04:47:34 UTC)

// Verification Directory fv/riscv_core 

module riscv_core(i_rstn, i_clk, o_imem_en, o_imem_addr, i_imem_read,
     o_dmem_en, o_dmem_we, o_dmem_addr, i_dmem_read, o_dmem_write,
     i_scan_en, i_test_mode, i_tdi, o_tdo, DFT_sdi_1, DFT_sdo_1,
     DFT_sdi_2, DFT_sdo_2, DFT_sdi_3, DFT_sdo_3, DFT_sdi_4, DFT_sdo_4,
     DFT_sdi_5, DFT_sdo_5, DFT_sdi_6, DFT_sdo_6, DFT_sdi_7, DFT_sdo_7,
     DFT_sdi_8, DFT_sdo_8, DFT_sdi_9, DFT_sdo_9, DFT_sdi_10,
     DFT_sdo_10);
  input i_rstn, i_clk, i_scan_en, i_test_mode, i_tdi, DFT_sdi_1,
       DFT_sdi_2, DFT_sdi_3, DFT_sdi_4, DFT_sdi_5, DFT_sdi_6,
       DFT_sdi_7, DFT_sdi_8, DFT_sdi_9, DFT_sdi_10;
  input [31:0] i_imem_read, i_dmem_read;
  output o_imem_en, o_dmem_en, o_dmem_we, o_tdo, DFT_sdo_1, DFT_sdo_2,
       DFT_sdo_3, DFT_sdo_4, DFT_sdo_5, DFT_sdo_6, DFT_sdo_7,
       DFT_sdo_8, DFT_sdo_9, DFT_sdo_10;
  output [8:0] o_imem_addr, o_dmem_addr;
  output [31:0] o_dmem_write;
  wire i_rstn, i_clk, i_scan_en, i_test_mode, i_tdi, DFT_sdi_1,
       DFT_sdi_2, DFT_sdi_3, DFT_sdi_4, DFT_sdi_5, DFT_sdi_6,
       DFT_sdi_7, DFT_sdi_8, DFT_sdi_9, DFT_sdi_10;
  wire [31:0] i_imem_read, i_dmem_read;
  wire o_imem_en, o_dmem_en, o_dmem_we, o_tdo, DFT_sdo_1, DFT_sdo_2,
       DFT_sdo_3, DFT_sdo_4, DFT_sdo_5, DFT_sdo_6, DFT_sdo_7,
       DFT_sdo_8, DFT_sdo_9, DFT_sdo_10;
  wire [8:0] o_imem_addr, o_dmem_addr;
  wire [31:0] o_dmem_write;
  wire [31:0] ex_to_me_result;
  wire [31:0] me_to_wb_alu_result;
  wire [31:0] id_to_ex_imm;
  wire [31:0] if_to_id_pc;
  wire [31:0] if_to_id_instr;
  wire [31:0] ex_to_if_pc_target;
  wire ex_to_if_pc_transfer, ex_to_me_we, id_to_ex_branch,
       id_to_ex_jump, id_to_ex_rw, id_to_ex_src_imm, n_0, n_1;
  wire n_2, n_4, n_5, n_6, n_15, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_201, n_553, u_execute_branch_taken,
       u_memory_o_dmem_we_339;
  assign o_tdo = 1'b0;
  assign o_dmem_write[0] = 1'b0;
  assign o_dmem_write[1] = 1'b0;
  assign o_dmem_write[2] = 1'b0;
  assign o_dmem_write[3] = 1'b0;
  assign o_dmem_write[4] = 1'b0;
  assign o_dmem_write[5] = 1'b0;
  assign o_dmem_write[6] = 1'b0;
  assign o_dmem_write[7] = 1'b0;
  assign o_dmem_write[8] = 1'b0;
  assign o_dmem_write[9] = 1'b0;
  assign o_dmem_write[10] = 1'b0;
  assign o_dmem_write[11] = 1'b0;
  assign o_dmem_write[12] = 1'b0;
  assign o_dmem_write[13] = 1'b0;
  assign o_dmem_write[14] = 1'b0;
  assign o_dmem_write[15] = 1'b0;
  assign o_dmem_write[16] = 1'b0;
  assign o_dmem_write[17] = 1'b0;
  assign o_dmem_write[18] = 1'b0;
  assign o_dmem_write[19] = 1'b0;
  assign o_dmem_write[20] = 1'b0;
  assign o_dmem_write[21] = 1'b0;
  assign o_dmem_write[22] = 1'b0;
  assign o_dmem_write[23] = 1'b0;
  assign o_dmem_write[24] = 1'b0;
  assign o_dmem_write[25] = 1'b0;
  assign o_dmem_write[26] = 1'b0;
  assign o_dmem_write[27] = 1'b0;
  assign o_dmem_write[28] = 1'b0;
  assign o_dmem_write[29] = 1'b0;
  assign o_dmem_write[30] = 1'b0;
  assign o_dmem_write[31] = 1'b0;
  assign o_imem_en = 1'b1;
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[10] (.RN (i_rstn), .CK
       (i_clk), .D (n_159), .SI (u_memory_o_dmem_we_339), .SE
       (i_scan_en), .Q (ex_to_me_result[10]));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[9] (.RN (i_rstn), .CK
       (i_clk), .D (n_158), .SI (me_to_wb_alu_result[10]), .SE
       (i_scan_en), .Q (ex_to_me_result[9]));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[8] (.RN (i_rstn), .CK
       (i_clk), .D (n_155), .SI (me_to_wb_alu_result[9]), .SE
       (i_scan_en), .Q (ex_to_me_result[8]));
  OAI2BB1X1 g6008__2398(.A0N (id_to_ex_imm[10]), .A1N (n_156), .B0
       (n_157), .Y (n_159));
  OAI2BB1X1 g6009__5107(.A0N (id_to_ex_imm[9]), .A1N (n_148), .B0
       (n_154), .Y (n_158));
  AOI22X1 g6015__6260(.A0 (n_153), .A1 (n_151), .B0 (n_152), .B1
       (ex_to_me_result[10]), .Y (n_157));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[7] (.RN (i_rstn), .CK
       (i_clk), .D (n_145), .SI (DFT_sdi_2), .SE (i_scan_en), .Q
       (ex_to_me_result[7]));
  OAI2BB1X1 g6028__4319(.A0N (n_147), .A1N (n_150), .B0 (n_146), .Y
       (n_156));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[6] (.RN (i_rstn), .CK
       (i_clk), .D (n_142), .SI (me_to_wb_alu_result[7]), .SE
       (i_scan_en), .Q (ex_to_me_result[6]));
  OAI2BB1X1 g6006__8428(.A0N (id_to_ex_imm[8]), .A1N (n_141), .B0
       (n_149), .Y (n_155));
  AOI22X1 g6020__5526(.A0 (n_153), .A1 (n_144), .B0 (n_152), .B1
       (ex_to_me_result[9]), .Y (n_154));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[5] (.RN (i_rstn), .CK
       (i_clk), .D (n_137), .SI (me_to_wb_alu_result[6]), .SE
       (i_scan_en), .Q (ex_to_me_result[5]));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[4] (.RN (i_rstn), .CK
       (i_clk), .D (n_138), .SI (me_to_wb_alu_result[5]), .SE
       (i_scan_en), .Q (ex_to_me_result[4]));
  NOR2X1 g6032__6783(.A (id_to_ex_imm[10]), .B (n_150), .Y (n_151));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[3] (.RN (i_rstn), .CK
       (i_clk), .D (n_139), .SI (DFT_sdi_3), .SE (i_scan_en), .Q
       (ex_to_me_result[3]));
  SDFFRHQX1 \u_execute_buffer_alu_result_reg[2] (.RN (i_rstn), .CK
       (i_clk), .D (n_136), .SI (me_to_wb_alu_result[3]), .SE
       (i_scan_en), .Q (ex_to_me_result[2]));
  AOI22X1 g6012__3680(.A0 (n_153), .A1 (n_135), .B0 (n_152), .B1
       (ex_to_me_result[8]), .Y (n_149));
  OAI2BB1X1 g6029__1617(.A0N (n_147), .A1N (n_143), .B0 (n_146), .Y
       (n_148));
  OAI2BB1X1 g6003__2802(.A0N (id_to_ex_imm[7]), .A1N (n_133), .B0
       (n_140), .Y (n_145));
  NOR2X1 g6036__1705(.A (id_to_ex_imm[9]), .B (n_143), .Y (n_144));
  NOR2BX1 g6037__5122(.AN (n_143), .B (id_to_ex_imm[9]), .Y (n_150));
  OAI2BB1X1 g6004__8246(.A0N (id_to_ex_imm[6]), .A1N (n_128), .B0
       (n_132), .Y (n_142));
  OAI2BB1X1 g6026__7098(.A0N (n_147), .A1N (n_134), .B0 (n_146), .Y
       (n_141));
  AOI22X1 g6017__6131(.A0 (n_153), .A1 (n_131), .B0 (n_152), .B1
       (ex_to_me_result[7]), .Y (n_140));
  OAI2BB1X1 g6010__1881(.A0N (id_to_ex_imm[3]), .A1N (n_124), .B0
       (n_127), .Y (n_139));
  OAI2BB1X1 g6011__5115(.A0N (id_to_ex_imm[4]), .A1N (n_126), .B0
       (n_121), .Y (n_138));
  OAI2BB1X1 g6005__7482(.A0N (id_to_ex_imm[5]), .A1N (n_129), .B0
       (n_122), .Y (n_137));
  OAI2BB1X1 g6007__4733(.A0N (id_to_ex_imm[2]), .A1N (n_123), .B0
       (n_125), .Y (n_136));
  NOR2X1 g6042__6161(.A (id_to_ex_imm[8]), .B (n_134), .Y (n_135));
  NOR2BX1 g6043__9315(.AN (n_134), .B (id_to_ex_imm[8]), .Y (n_143));
  OAI2BB1X1 g6025__9945(.A0N (n_147), .A1N (n_130), .B0 (n_146), .Y
       (n_133));
  AOI22X1 g6013__2883(.A0 (n_153), .A1 (n_119), .B0 (n_152), .B1
       (ex_to_me_result[6]), .Y (n_132));
  NOR2X1 g6045__2346(.A (id_to_ex_imm[7]), .B (n_130), .Y (n_131));
  NOR2BX1 g6048__1666(.AN (n_130), .B (id_to_ex_imm[7]), .Y (n_134));
  OAI2BB1X1 g6023__7410(.A0N (n_147), .A1N (n_117), .B0 (n_146), .Y
       (n_129));
  OAI2BB1X1 g6022__6417(.A0N (n_147), .A1N (n_120), .B0 (n_146), .Y
       (n_128));
  AOI22X1 g6021__5477(.A0 (n_113), .A1 (n_153), .B0 (n_152), .B1
       (ex_to_me_result[3]), .Y (n_127));
  OAI2BB1X1 g6024__2398(.A0N (n_114), .A1N (n_147), .B0 (n_146), .Y
       (n_126));
  AOI22X1 g6014__5107(.A0 (n_108), .A1 (n_153), .B0 (n_152), .B1
       (ex_to_me_result[2]), .Y (n_125));
  OAI2BB1X1 g6030__6260(.A0N (n_112), .A1N (n_147), .B0 (n_146), .Y
       (n_124));
  OAI2BB1X1 g6027__4319(.A0N (n_107), .A1N (n_147), .B0 (n_146), .Y
       (n_123));
  AOI22X1 g6018__8428(.A0 (n_153), .A1 (n_118), .B0 (n_152), .B1
       (ex_to_me_result[5]), .Y (n_122));
  AOI22X1 g6019__5526(.A0 (n_115), .A1 (n_153), .B0 (n_152), .B1
       (ex_to_me_result[4]), .Y (n_121));
  NOR2BX1 g6052__6783(.AN (n_120), .B (id_to_ex_imm[6]), .Y (n_130));
  NOR2X1 g6050__3680(.A (id_to_ex_imm[6]), .B (n_120), .Y (n_119));
  OR2X2 g6034__1617(.A (DFT_sdo_3), .B (n_116), .Y (n_146));
  NOR2X1 g6053__2802(.A (id_to_ex_imm[5]), .B (n_117), .Y (n_118));
  NOR2BX1 g6055__1705(.AN (n_117), .B (id_to_ex_imm[5]), .Y (n_120));
  AND2X2 g6035__5122(.A (DFT_sdo_3), .B (n_147), .Y (n_153));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[10] (.RN (i_rstn), .CK (i_clk), .D
       (n_111), .SI (if_to_id_pc[9]), .SE (i_scan_en), .Q
       (if_to_id_pc[10]));
  INVX1 g6038(.A (n_147), .Y (n_116));
  NOR2X1 g6060__8246(.A (id_to_ex_imm[4]), .B (n_114), .Y (n_115));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[3] (.RN (i_rstn), .CK (i_clk), .D
       (n_109), .SI (DFT_sdi_10), .SE (i_scan_en), .Q (if_to_id_pc[3]));
  NOR2BX1 g6061__7098(.AN (n_114), .B (id_to_ex_imm[4]), .Y (n_117));
  AND3X2 g6041__6131(.A (id_to_ex_src_imm), .B (id_to_ex_rw), .C
       (n_110), .Y (n_147));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[6] (.RN (i_rstn), .CK (i_clk), .D
       (n_106), .SI (if_to_id_pc[5]), .SE (i_scan_en), .Q
       (if_to_id_pc[6]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[2] (.RN (i_rstn), .CK (i_clk), .D
       (n_105), .SI (if_to_id_instr[31]), .SE (i_scan_en), .Q
       (DFT_sdo_9));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[9] (.RN (i_rstn), .CK (i_clk), .D
       (n_103), .SI (if_to_id_pc[8]), .SE (i_scan_en), .Q
       (if_to_id_pc[9]));
  NOR2X1 g6063__1881(.A (id_to_ex_imm[3]), .B (n_112), .Y (n_113));
  NOR2BX1 g6064__5115(.AN (n_112), .B (id_to_ex_imm[3]), .Y (n_114));
  MX2X1 g6031__7482(.A (n_102), .B (ex_to_if_pc_target[10]), .S0
       (ex_to_if_pc_transfer), .Y (n_111));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[4] (.RN (i_rstn), .CK (i_clk), .D
       (n_100), .SI (if_to_id_pc[3]), .SE (i_scan_en), .Q
       (if_to_id_pc[4]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[7] (.RN (i_rstn), .CK (i_clk), .D
       (n_101), .SI (if_to_id_pc[6]), .SE (i_scan_en), .Q
       (if_to_id_pc[7]));
  NOR2X1 g6047__4733(.A (DFT_sdo_1), .B (DFT_sdo_2), .Y (n_110));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[5] (.RN (i_rstn), .CK (i_clk), .D
       (n_99), .SI (if_to_id_pc[4]), .SE (i_scan_en), .Q
       (if_to_id_pc[5]));
  SDFFRHQX1 \u_fetch_u_add_pc_reg[8] (.RN (i_rstn), .CK (i_clk), .D
       (n_98), .SI (if_to_id_pc[7]), .SE (i_scan_en), .Q
       (if_to_id_pc[8]));
  MX2X1 g6068__6161(.A (n_18), .B (ex_to_if_pc_target[3]), .S0
       (ex_to_if_pc_transfer), .Y (n_109));
  NOR2X1 g6071__9315(.A (id_to_ex_imm[2]), .B (n_107), .Y (n_108));
  NOR2BX1 g6072__9945(.AN (n_107), .B (id_to_ex_imm[2]), .Y (n_112));
  MX2X1 g6067__2883(.A (n_47), .B (ex_to_if_pc_target[6]), .S0
       (ex_to_if_pc_transfer), .Y (n_106));
  MXI2XL g6069__2346(.A (DFT_sdo_9), .B (ex_to_if_pc_target[2]), .S0
       (ex_to_if_pc_transfer), .Y (n_105));
  SDFFQX1 \u_decode_o_alu_op_buffer_2_reg[0] (.CK (i_clk), .D (n_95),
       .SI (me_to_wb_alu_result[8]), .SE (i_scan_en), .Q (DFT_sdo_1));
  NOR2X1 g6081__1666(.A (DFT_sdo_4), .B (DFT_sdo_5), .Y (n_107));
  MX2X1 g6039__7410(.A (n_97), .B (ex_to_if_pc_target[9]), .S0
       (ex_to_if_pc_transfer), .Y (n_103));
  CLKXOR2X1 g6040__6417(.A (if_to_id_pc[10]), .B (n_96), .Y (n_102));
  MX2X1 g6070__5477(.A (n_66), .B (ex_to_if_pc_target[7]), .S0
       (ex_to_if_pc_transfer), .Y (n_101));
  MX2X1 g6074__2398(.A (n_24), .B (ex_to_if_pc_target[4]), .S0
       (ex_to_if_pc_transfer), .Y (n_100));
  MX2X1 g6075__5107(.A (n_31), .B (ex_to_if_pc_target[5]), .S0
       (ex_to_if_pc_transfer), .Y (n_99));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[3] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[3]), .Q (ex_to_if_pc_target[3]));
  MX2X1 g6051__6260(.A (n_93), .B (ex_to_if_pc_target[8]), .S0
       (ex_to_if_pc_transfer), .Y (n_98));
  DFFRX1 \u_execute_buffer_pc_target_reg[2] (.RN (i_rstn), .CK (i_clk),
       .D (id_to_ex_imm[2]), .Q (n_201), .QN (ex_to_if_pc_target[2]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[6] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[6]), .Q (ex_to_if_pc_target[6]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[10] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[10]), .Q (ex_to_if_pc_target[10]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[1] (.CK (i_clk), .D (n_94), .SI
       (u_execute_branch_taken), .SE (i_scan_en), .Q (DFT_sdo_5));
  ADDHX1 g6044__4319(.A (if_to_id_pc[9]), .B (n_92), .CO (n_96), .S
       (n_97));
  OAI32X1 g6054__8428(.A0 (if_to_id_instr[2]), .A1
       (if_to_id_instr[30]), .A2 (n_91), .B0 (if_to_id_instr[12]), .B1
       (n_52), .Y (n_95));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[0] (.CK (i_clk), .D (n_90), .SI
       (ex_to_if_pc_target[5]), .SE (i_scan_en), .Q (DFT_sdo_4));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[3] (.CK (i_clk), .D (n_88), .SI
       (ex_to_if_pc_target[4]), .SE (i_scan_en), .Q (id_to_ex_imm[3]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[8] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[8]), .Q (ex_to_if_pc_target[8]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[4] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[4]), .Q (ex_to_if_pc_target[4]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[5] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[5]), .Q (ex_to_if_pc_target[5]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[7] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[7]), .Q (ex_to_if_pc_target[7]));
  DFFRHQX1 \u_execute_buffer_pc_target_reg[9] (.RN (i_rstn), .CK
       (i_clk), .D (id_to_ex_imm[9]), .Q (ex_to_if_pc_target[9]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[10] (.CK (i_clk), .D (n_84), .SI
       (me_to_wb_alu_result[2]), .SE (i_scan_en), .Q
       (id_to_ex_imm[10]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[2] (.CK (i_clk), .D (n_87), .SI
       (ex_to_if_pc_target[3]), .SE (i_scan_en), .Q (id_to_ex_imm[2]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[6] (.CK (i_clk), .D (n_83), .SI
       (ex_to_if_pc_target[7]), .SE (i_scan_en), .Q (id_to_ex_imm[6]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[8] (.CK (i_clk), .D (n_69), .SI
       (DFT_sdi_4), .SE (i_scan_en), .Q (id_to_ex_imm[8]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[7] (.CK (i_clk), .D (n_75), .SI
       (ex_to_if_pc_target[8]), .SE (i_scan_en), .Q (id_to_ex_imm[7]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[9] (.CK (i_clk), .D (n_67), .SI
       (ex_to_if_pc_target[10]), .SE (i_scan_en), .Q (id_to_ex_imm[9]));
  OAI221X1 g6101__5526(.A0 (if_to_id_instr[9]), .A1 (n_86), .B0
       (if_to_id_instr[13]), .B1 (n_89), .C0 (n_553), .Y (n_94));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[5] (.CK (i_clk), .D (n_68), .SI
       (ex_to_if_pc_target[6]), .SE (i_scan_en), .Q (id_to_ex_imm[5]));
  SDFFQX1 \u_decode_o_imm_buffer_2_reg[4] (.CK (i_clk), .D (n_72), .SI
       (DFT_sdi_5), .SE (i_scan_en), .Q (id_to_ex_imm[4]));
  ADDHX1 g6056__6783(.A (if_to_id_pc[8]), .B (n_65), .CO (n_92), .S
       (n_93));
  OR4X1 g6073__3680(.A (if_to_id_instr[27]), .B (if_to_id_instr[28]),
       .C (if_to_id_instr[29]), .D (n_73), .Y (n_91));
  OAI221X1 g6099__1617(.A0 (if_to_id_instr[12]), .A1 (n_89), .B0
       (if_to_id_instr[21]), .B1 (n_85), .C0 (n_80), .Y (n_90));
  OAI211X1 g6100__2802(.A0 (if_to_id_instr[23]), .A1 (n_63), .B0
       (n_45), .C0 (n_79), .Y (n_88));
  DFFRHQX1 u_memory_o_dmem_we_reg(.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_we), .Q (u_memory_o_dmem_we_339));
  OAI221X1 g6093__1705(.A0 (n_22), .A1 (n_86), .B0
       (if_to_id_instr[23]), .B1 (n_85), .C0 (n_70), .Y (n_87));
  OAI221X1 g6102__5122(.A0 (if_to_id_instr[30]), .A1 (n_54), .B0
       (n_62), .B1 (n_89), .C0 (n_44), .Y (n_84));
  OAI2BB1X1 g6103__8246(.A0N (if_to_id_instr[27]), .A1N (n_59), .B0
       (n_77), .Y (n_83));
  SDFFQX1 \u_decode_o_alu_op_buffer_2_reg[1] (.CK (i_clk), .D (n_51),
       .SI (me_to_wb_alu_result[4]), .SE (i_scan_en), .Q (DFT_sdo_2));
  AOI222X1 g6111__6131(.A0 (if_to_id_instr[8]), .A1 (n_49), .B0
       (if_to_id_instr[7]), .B1 (n_78), .C0 (if_to_id_instr[20]), .C1
       (n_61), .Y (n_80));
  AOI22X1 g6119__1881(.A0 (if_to_id_instr[10]), .A1 (n_78), .B0
       (if_to_id_instr[15]), .B1 (n_76), .Y (n_79));
  AOI22X1 g6115__5115(.A0 (if_to_id_instr[26]), .A1 (n_74), .B0
       (if_to_id_instr[18]), .B1 (n_76), .Y (n_77));
  OAI2BB1X1 g6113__7482(.A0N (if_to_id_instr[27]), .A1N (n_74), .B0
       (n_58), .Y (n_75));
  DFFRHQX1 u_execute_buffer_we_reg(.RN (i_rstn), .CK (i_clk), .D
       (id_to_ex_rw), .Q (ex_to_me_we));
  OR4X1 g6104__4733(.A (DFT_sdo_7), .B (if_to_id_instr[25]), .C
       (if_to_id_instr[26]), .D (n_50), .Y (n_73));
  OAI221X1 g6108__6161(.A0 (n_20), .A1 (n_71), .B0
       (if_to_id_instr[16]), .B1 (n_89), .C0 (n_60), .Y (n_72));
  OA21X1 g6107__9315(.A0 (if_to_id_instr[9]), .A1 (n_71), .B0 (n_57),
       .Y (n_70));
  OAI2BB1X1 g6106__9945(.A0N (if_to_id_instr[28]), .A1N (n_74), .B0
       (n_55), .Y (n_69));
  OAI2BB1X1 g6109__2883(.A0N (if_to_id_instr[25]), .A1N (n_74), .B0
       (n_56), .Y (n_68));
  OAI2BB1X1 g6112__2346(.A0N (if_to_id_instr[29]), .A1N (n_74), .B0
       (n_53), .Y (n_67));
  ADDHX1 g6076__1666(.A (if_to_id_pc[7]), .B (n_46), .CO (n_65), .S
       (n_66));
  OA22X1 g6116__7410(.A0 (if_to_id_instr[21]), .A1 (n_63), .B0 (n_62),
       .B1 (n_85), .Y (n_64));
  SDFFQX1 u_decode_o_src_imm_buffer_2_reg(.CK (i_clk), .D (n_61), .SI
       (id_to_ex_jump), .SE (i_scan_en), .Q (id_to_ex_src_imm));
  SDFFQX1 u_decode_o_arith_buffer_2_reg(.CK (i_clk), .D (n_41), .SI
       (ex_to_if_pc_target[9]), .SE (i_scan_en), .Q (DFT_sdo_3));
  INVX2 g6136(.A (id_to_ex_rw), .Y (n_152));
  SDFFRHQX2 u_execute_buffer_pc_transfer_reg(.RN (i_rstn), .CK (i_clk),
       .D (n_39), .SI (id_to_ex_src_imm), .SE (i_scan_en), .Q
       (ex_to_if_pc_transfer));
  AOI22X1 g6122__6417(.A0 (if_to_id_instr[25]), .A1 (n_59), .B0
       (if_to_id_instr[24]), .B1 (n_61), .Y (n_60));
  AOI22X1 g6121__5477(.A0 (if_to_id_instr[28]), .A1 (n_59), .B0
       (if_to_id_instr[19]), .B1 (n_76), .Y (n_58));
  AOI22X1 g6120__2398(.A0 (if_to_id_instr[22]), .A1 (n_61), .B0
       (DFT_sdo_7), .B1 (n_76), .Y (n_57));
  AOI22X1 g6123__5107(.A0 (if_to_id_instr[26]), .A1 (n_59), .B0
       (if_to_id_instr[17]), .B1 (n_76), .Y (n_56));
  AOI22X1 g6124__6260(.A0 (if_to_id_instr[29]), .A1 (n_59), .B0
       (if_to_id_instr[20]), .B1 (n_76), .Y (n_55));
  INVX1 g6126(.A (n_74), .Y (n_54));
  OA22X1 g6125__4319(.A0 (if_to_id_instr[30]), .A1 (n_42), .B0
       (if_to_id_instr[21]), .B1 (n_89), .Y (n_53));
  DFFRHQX1 u_execute_branch_taken_reg(.RN (i_rstn), .CK (i_clk), .D
       (id_to_ex_branch), .Q (u_execute_branch_taken));
  INVX1 g6131(.A (n_51), .Y (n_52));
  SDFFQX1 u_decode_o_rw_buffer_2_reg(.CK (i_clk), .D (n_36), .SI
       (DFT_sdi_1), .SE (i_scan_en), .Q (id_to_ex_rw));
  NAND3X1 g6133__8428(.A (if_to_id_instr[13]), .B (if_to_id_instr[12]),
       .C (n_38), .Y (n_50));
  OR2X1 g6129__5526(.A (n_48), .B (n_61), .Y (n_74));
  NOR3BX1 g6135__6783(.AN (DFT_sdo_7), .B (if_to_id_instr[13]), .C
       (n_40), .Y (n_51));
  INVX1 g6141(.A (n_71), .Y (n_78));
  INVX1 g6143(.A (n_61), .Y (n_63));
  SDFFQX1 u_decode_o_branch_buffer_2_reg(.CK (i_clk), .D (n_49), .SI
       (n_201), .SE (i_scan_en), .Q (id_to_ex_branch));
  NAND2X2 g6145__3680(.A (DFT_sdo_6), .B (n_48), .Y (n_71));
  ADDHX1 g6105__1617(.A (if_to_id_pc[6]), .B (n_30), .CO (n_46), .S
       (n_47));
  AOI22X1 g6132__2802(.A0 (if_to_id_instr[11]), .A1 (n_49), .B0
       (if_to_id_instr[24]), .B1 (n_43), .Y (n_45));
  AOI22X1 g6134__1705(.A0 (if_to_id_instr[7]), .A1 (n_49), .B0
       (if_to_id_instr[20]), .B1 (n_43), .Y (n_44));
  INVX1 g6142(.A (n_59), .Y (n_42));
  INVX1 g6148(.A (n_40), .Y (n_41));
  OR2X1 g6144__5122(.A (id_to_ex_jump), .B (u_execute_branch_taken), .Y
       (n_39));
  INVX1 g6154(.A (n_89), .Y (n_76));
  AO22X1 g6147__8246(.A0 (if_to_id_instr[2]), .A1 (n_32), .B0 (n_19),
       .B1 (n_37), .Y (n_61));
  NOR2BX1 g6151__7098(.AN (n_35), .B (if_to_id_instr[31]), .Y (n_38));
  NAND2X1 g6152__6131(.A (if_to_id_instr[4]), .B (n_37), .Y (n_40));
  OR2X1 g6146__1881(.A (n_43), .B (n_49), .Y (n_59));
  AND2X1 g6155__5115(.A (n_37), .B (n_34), .Y (n_36));
  NOR2BX1 g6156__7482(.AN (n_37), .B (if_to_id_instr[4]), .Y (n_48));
  NAND2X2 g6158__4733(.A (if_to_id_instr[2]), .B (n_35), .Y (n_89));
  SDFFQX1 u_decode_o_jump_buffer_2_reg(.CK (i_clk), .D (n_29), .SI
       (DFT_sdi_6), .SE (i_scan_en), .Q (id_to_ex_jump));
  INVX1 g6159(.A (n_49), .Y (n_86));
  NOR2X1 g6160__6161(.A (n_34), .B (n_33), .Y (n_35));
  INVX1 g6153(.A (n_85), .Y (n_43));
  NOR2X1 g6163__9315(.A (if_to_id_instr[2]), .B (n_33), .Y (n_37));
  AND2X1 g6161__9945(.A (n_32), .B (n_27), .Y (n_49));
  ADDHX1 g6137__2883(.A (if_to_id_pc[5]), .B (n_23), .CO (n_30), .S
       (n_31));
  NAND2X2 g6157__2346(.A (if_to_id_instr[3]), .B (n_29), .Y (n_85));
  NAND2BX1 g6165__1666(.AN (if_to_id_instr[6]), .B (n_28), .Y (n_33));
  NOR2BX1 g6166__7410(.AN (n_28), .B (n_26), .Y (n_32));
  NOR4X2 g6162__6417(.A (n_27), .B (i_rstn), .C (n_25), .D (n_26), .Y
       (n_29));
  NOR3X1 g6167__5477(.A (if_to_id_instr[3]), .B (i_rstn), .C (n_25), .Y
       (n_28));
  ADDHX1 g6164__2398(.A (if_to_id_pc[4]), .B (n_17), .CO (n_23), .S
       (n_24));
  NAND3BX2 g6168__5107(.AN (if_to_id_instr[4]), .B (DFT_sdo_6), .C
       (if_to_id_instr[6]), .Y (n_26));
  NAND2X1 g6170__6260(.A (if_to_id_instr[4]), .B (DFT_sdo_6), .Y
       (n_34));
  NAND2X1 g6171__4319(.A (if_to_id_instr[0]), .B (if_to_id_instr[1]),
       .Y (n_25));
  INVX1 g6172(.A (if_to_id_instr[10]), .Y (n_22));
  INVX1 g6174(.A (if_to_id_instr[2]), .Y (n_27));
  INVX1 g6173(.A (if_to_id_instr[22]), .Y (n_62));
  INVX1 g6191(.A (if_to_id_instr[8]), .Y (n_21));
  INVX1 g6192(.A (if_to_id_instr[11]), .Y (n_20));
  INVX1 g6193(.A (DFT_sdo_6), .Y (n_19));
  ADDHX1 g6169__8428(.A (DFT_sdo_9), .B (if_to_id_pc[3]), .CO (n_17),
       .S (n_18));
  SDFFRHQX1 u_memory_o_dmem_en_reg(.RN (i_rstn), .CK (i_clk), .D
       (1'b1), .SI (if_to_id_pc[10]), .SE (i_scan_en), .Q (DFT_sdo_10));
  SDFFRXL \u_fetch_InstructionBuffer_reg[16] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[16]), .SI (if_to_id_instr[15]), .SE (i_scan_en),
       .Q (n_6), .QN (if_to_id_instr[16]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[18] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[18]), .SI (if_to_id_instr[17]), .SE
       (i_scan_en), .Q (if_to_id_instr[18]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[17] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[17]), .SI (n_6), .SE (i_scan_en), .Q
       (if_to_id_instr[17]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[19] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[19]), .SI (if_to_id_instr[18]), .SE
       (i_scan_en), .Q (if_to_id_instr[19]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[1] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[1]), .SI (if_to_id_instr[0]), .SE (i_scan_en),
       .Q (if_to_id_instr[1]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[22] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[22]), .SI (n_2), .SE (i_scan_en), .Q
       (if_to_id_instr[22]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[6] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[6]), .SI (DFT_sdi_7), .SE (i_scan_en), .Q
       (if_to_id_instr[6]));
  SDFFRXL \u_fetch_InstructionBuffer_reg[9] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[9]), .SI (if_to_id_instr[8]), .SE (i_scan_en),
       .Q (n_5), .QN (if_to_id_instr[9]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[7] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[7]), .SI (if_to_id_instr[6]), .SE (i_scan_en),
       .Q (if_to_id_instr[7]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[10] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[10]), .SI (n_5), .SE (i_scan_en), .Q
       (if_to_id_instr[10]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[28] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[28]), .SI (if_to_id_instr[27]), .SE
       (i_scan_en), .Q (if_to_id_instr[28]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[29] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[29]), .SI (if_to_id_instr[28]), .SE
       (i_scan_en), .Q (if_to_id_instr[29]));
  SDFFRXL \u_fetch_InstructionBuffer_reg[30] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[30]), .SI (if_to_id_instr[29]), .SE (i_scan_en),
       .Q (n_4), .QN (if_to_id_instr[30]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[14] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[14]), .SI (n_1), .SE (i_scan_en), .Q
       (DFT_sdo_7));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[2] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[2]), .SI (if_to_id_instr[1]), .SE (i_scan_en),
       .Q (if_to_id_instr[2]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[15] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[15]), .SI (DFT_sdi_8), .SE (i_scan_en),
       .Q (if_to_id_instr[15]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[0] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[0]), .SI (ex_to_if_pc_transfer), .SE
       (i_scan_en), .Q (if_to_id_instr[0]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[31] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[31]), .SI (n_4), .SE (i_scan_en), .Q
       (if_to_id_instr[31]));
  SDFFRXL \u_fetch_InstructionBuffer_reg[23] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[23]), .SI (if_to_id_instr[22]), .SE (i_scan_en),
       .Q (DFT_sdo_8), .QN (if_to_id_instr[23]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[8] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[8]), .SI (if_to_id_instr[7]), .SE (i_scan_en),
       .Q (if_to_id_instr[8]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[3] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[3]), .SI (if_to_id_instr[2]), .SE (i_scan_en),
       .Q (if_to_id_instr[3]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[11] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[11]), .SI (if_to_id_instr[10]), .SE
       (i_scan_en), .Q (if_to_id_instr[11]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[24] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[24]), .SI (DFT_sdi_9), .SE (i_scan_en),
       .Q (if_to_id_instr[24]));
  SDFFRXL \u_fetch_InstructionBuffer_reg[21] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[21]), .SI (if_to_id_instr[20]), .SE (i_scan_en),
       .Q (n_2), .QN (if_to_id_instr[21]));
  SDFFRXL \u_fetch_InstructionBuffer_reg[13] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[13]), .SI (n_0), .SE (i_scan_en), .Q (n_1), .QN
       (if_to_id_instr[13]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[27] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[27]), .SI (if_to_id_instr[26]), .SE
       (i_scan_en), .Q (if_to_id_instr[27]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[20] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[20]), .SI (if_to_id_instr[19]), .SE
       (i_scan_en), .Q (if_to_id_instr[20]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[26] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[26]), .SI (if_to_id_instr[25]), .SE
       (i_scan_en), .Q (if_to_id_instr[26]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[25] (.RN (n_15), .CK
       (i_clk), .D (i_imem_read[25]), .SI (if_to_id_instr[24]), .SE
       (i_scan_en), .Q (if_to_id_instr[25]));
  SDFFRXL \u_fetch_InstructionBuffer_reg[12] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[12]), .SI (if_to_id_instr[11]), .SE (i_scan_en),
       .Q (n_0), .QN (if_to_id_instr[12]));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[5] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[5]), .SI (if_to_id_instr[4]), .SE (i_scan_en),
       .Q (DFT_sdo_6));
  SDFFRHQX1 \u_fetch_InstructionBuffer_reg[4] (.RN (n_15), .CK (i_clk),
       .D (i_imem_read[4]), .SI (if_to_id_instr[3]), .SE (i_scan_en),
       .Q (if_to_id_instr[4]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[4] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[6]), .Q (me_to_wb_alu_result[6]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[8] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[10]), .Q (me_to_wb_alu_result[10]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[6] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[8]), .Q (me_to_wb_alu_result[8]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[3] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[5]), .Q (me_to_wb_alu_result[5]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[5] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[7]), .Q (me_to_wb_alu_result[7]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[7] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[9]), .Q (me_to_wb_alu_result[9]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[2] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[4]), .Q (me_to_wb_alu_result[4]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[0] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[2]), .Q (me_to_wb_alu_result[2]));
  DFFRHQX1 \u_memory_o_dmem_addr_reg[1] (.RN (i_rstn), .CK (i_clk), .D
       (ex_to_me_result[3]), .Q (me_to_wb_alu_result[3]));
  NAND2BXL g6220__5526(.AN (i_scan_en), .B (i_rstn), .Y (n_15));
  CLKBUFX20 drc_bufs6323(.A (DFT_sdo_9), .Y (o_imem_addr[0]));
  CLKBUFX20 drc_bufs6328(.A (me_to_wb_alu_result[3]), .Y
       (o_dmem_addr[1]));
  CLKBUFX20 drc_bufs6333(.A (me_to_wb_alu_result[9]), .Y
       (o_dmem_addr[7]));
  CLKBUFX20 drc_bufs6338(.A (me_to_wb_alu_result[10]), .Y
       (o_dmem_addr[8]));
  CLKBUFX20 drc_bufs6343(.A (me_to_wb_alu_result[5]), .Y
       (o_dmem_addr[3]));
  CLKBUFX20 drc_bufs6348(.A (me_to_wb_alu_result[6]), .Y
       (o_dmem_addr[4]));
  CLKBUFX20 drc_bufs6353(.A (u_memory_o_dmem_we_339), .Y (o_dmem_we));
  CLKBUFX20 drc_bufs6358(.A (me_to_wb_alu_result[7]), .Y
       (o_dmem_addr[5]));
  CLKBUFX20 drc_bufs6363(.A (me_to_wb_alu_result[2]), .Y
       (o_dmem_addr[0]));
  CLKBUFX20 drc_bufs6368(.A (me_to_wb_alu_result[4]), .Y
       (o_dmem_addr[2]));
  CLKBUFX20 drc_bufs6373(.A (me_to_wb_alu_result[8]), .Y
       (o_dmem_addr[6]));
  CLKBUFX20 drc_bufs(.A (if_to_id_pc[10]), .Y (o_imem_addr[8]));
  CLKBUFX20 drc_bufs6378(.A (if_to_id_pc[6]), .Y (o_imem_addr[4]));
  CLKBUFX20 drc_bufs6381(.A (if_to_id_pc[7]), .Y (o_imem_addr[5]));
  CLKBUFX20 drc_bufs6384(.A (if_to_id_pc[9]), .Y (o_imem_addr[7]));
  CLKBUFX20 drc_bufs6387(.A (if_to_id_pc[8]), .Y (o_imem_addr[6]));
  CLKBUFX20 drc_bufs6390(.A (if_to_id_pc[4]), .Y (o_imem_addr[2]));
  CLKBUFX20 drc_bufs6393(.A (if_to_id_pc[5]), .Y (o_imem_addr[3]));
  CLKBUFX20 drc_bufs6402(.A (if_to_id_pc[3]), .Y (o_imem_addr[1]));
  CLKBUFX20 drc_bufs6405(.A (DFT_sdo_10), .Y (o_dmem_en));
  OA21X1 g2(.A0 (n_21), .A1 (n_71), .B0 (n_64), .Y (n_553));
endmodule

